/**
 * \author Mr.Nobody
 * \file Rcc_ClkMux.c
 * \ingroup Rcc
 * \brief Rcc module ClkMux component functionality.
 *
 * The ClkMux component controls the peripheral kernel clock multiplexers
 * (clock source selection fields in the RCC D1CCIPR / D2CCIP1R / D2CCIP2R /
 * D3CCIPR - CDCCIPR / CDCCIP1R / CDCCIP2R / SRDCCIPR, CCIPR1 - CCIPR4 on
 * STM32H7R / H7S - and BDCR registers).
 * All MCU specific knowledge is stored in the constant array
 * rcc_ClkMuxConfig[]; the functions only look up a record and read or write
 * the register field described by that record.
 *
 * \par Structure of rcc_ClkMuxConfig[]
 * One record (rcc_ClkMuxConfigStruct_t) describes one selectable clock source
 * of one clock multiplexer:
 * - ClkMuxId        - ID of this record (rcc_ClkMuxId_t, Rcc_ClkMux.h).
 * - BlockId         - Peripheral block clocked through this multiplexer
 *                     (rcc_BlockList_t, Rcc.h) - the first peripheral of a
 *                     multiplexer shared by several peripherals.
 * - ClkMuxRegId     - RCC register containing the multiplexer field.
 * - ClkSrcMask      - Bit mask of the multiplexer field in that register.
 * - ClkSrcVal       - Value selecting this clock source - either the raw field
 *                     value (within ClkSrcMask, RTC) or the LL_CLKSOURCE()
 *                     encoded value (register offset, position, mask and field
 *                     value). Both forms are converted to the field value by
 *                     Rcc_ClkMux_Get_FieldVal().
 * - DefaultClkMuxId - Record holding the default (reset) selection of this
 *                     multiplexer.
 *
 * Records of the kernel clock selection registers are written by
 * \ref RCC_CLK_MUX_RECORD from the LL_CLKSOURCE() encoded clock source - register
 * and mask of the record are derived from the encoded value. Multiplexers which
 * LL does not encode (raw field values) are encoded by LL_CLKSOURCE() with the
 * register / field of the selected device line.
 *
 * Records belonging to one multiplexer form a group. They share the same
 * BlockId, ClkMuxRegId, ClkSrcMask and DefaultClkMuxId and differ only in
 * ClkMuxId and ClkSrcVal. The default record is the first record of the
 * group.
 *
 * \par Rules for adding or changing records
 * - The records must be in exactly the same order as rcc_ClkMuxId_t, because
 *   the array is indexed directly by ClkMuxId. Rcc_ClkMux_Init() verifies
 *   that rcc_ClkMuxConfig[ i ].ClkMuxId == i and a _Static_assert verifies
 *   the size of the array.
 * - The kernel clock tables are generated from the CMSIS / LL headers of all
 *   STM32H7 devices (guards select the records of the device).
 *
 */
/* ============================== INCLUDES ================================== */
#include "Rcc_ClkMux.h"                     /* Self include                   */
#include "Rcc_Port.h"                       /* Own port file include          */
#include "Rcc_Types.h"                      /* Module types definitions       */
#include "Rcc_Reg.h"                        /* Registry operations include    */
#include "Rcc.h"                            /* Module common header file      */
/* ========================== SYMBOLIC CONSTANTS ============================ */

/** Maximal wait time for configuration request confirmation */
#define RCC_CLKMUX_TIMEOUT_RAW             ( 0x84FCB )

/** Byte offset between consecutive kernel clock selection registers */
#define RCC_CLKMUX_REG_OFFSET_SHIFT        ( 2u )

/* ============================== TYPEDEFS ================================== */

/**
 * \brief Clock tree configuration structure
 */
typedef struct __attribute__((packed))
{
    rcc_ClkMuxId_t          ClkMuxId;         /**< Peripheral ID                    */
    rcc_BlockList_t         BlockId;          /**< Peripheral block ID              */
    rcc_RegId_t             ClkMuxRegId;      /**< Clock MUX register ID.           */
    volatile uint32_t const ClkSrcMask;       /**< Clock MUX bit mask.              */
    volatile uint32_t const ClkSrcVal;        /**< Clock MUX value.                 */
    rcc_ClkMuxId_t          DefaultClkMuxId;  /**< Peripheral default configuration */
}   rcc_ClkMuxConfigStruct_t;

/* ======================== FORWARD DECLARATIONS ============================ */

static uint32_t           Rcc_ClkMux_Get_FieldVal ( rcc_ClkMuxId_t clkMuxId );
static rcc_RequestState_t Rcc_ClkMux_Check_Record ( rcc_ClkMuxId_t clkMuxId );

/* =============================== MACROS =================================== */

/**
 * \brief Record of a kernel clock selection register multiplexer input.
 *
 * \param muxId     [in]: Record ID (\ref rcc_ClkMuxId_t)
 * \param blockId   [in]: Peripheral block of the multiplexer (\ref rcc_BlockList_t)
 * \param llClkSrc  [in]: LL_CLKSOURCE() encoded clock source
 * \param dfltMuxId [in]: Record ID of the default selection of the multiplexer
 */
#define RCC_CLK_MUX_RECORD( muxId, blockId, llClkSrc, dfltMuxId )                                                   \
    { .ClkMuxId        = ( muxId ),                                                                                 \
      .BlockId         = ( blockId ),                                                                               \
      .ClkMuxRegId     = (rcc_RegId_t)( (uint32_t)RCC_REG_D1CCIPR + ( LL_CLKSOURCE_REG( llClkSrc ) >> RCC_CLKMUX_REG_OFFSET_SHIFT ) ), \
      .ClkSrcMask      = LL_CLKSOURCE_MASK( llClkSrc ),                                                             \
      .ClkSrcVal       = ( llClkSrc ),                                                                              \
      .DefaultClkMuxId = ( dfltMuxId ) }

/* ========================== EXPORTED VARIABLES ============================ */

/* =========================== LOCAL VARIABLES ============================== */

/** \brief Configuration array of MCU peripherals with available clock MUX. */
static const rcc_ClkMuxConfigStruct_t   rcc_ClkMuxConfig[ ] =
{
  /*------------------------------ System core ------------------------------*/
  { .ClkMuxId = RCC_CLK_MUX_RTC_NONE          , .BlockId = RCC_BLOCK_RTCAPB   , .ClkMuxRegId = RCC_REG_BDCR     , .ClkSrcMask = RCC_BDCR_RTCSEL        , .ClkSrcVal = LL_RCC_RTC_CLKSOURCE_NONE         , .DefaultClkMuxId = RCC_CLK_MUX_RTC_NONE          },
  { .ClkMuxId = RCC_CLK_MUX_RTC_HSE_DIV       , .BlockId = RCC_BLOCK_RTCAPB   , .ClkMuxRegId = RCC_REG_BDCR     , .ClkSrcMask = RCC_BDCR_RTCSEL        , .ClkSrcVal = LL_RCC_RTC_CLKSOURCE_HSE          , .DefaultClkMuxId = RCC_CLK_MUX_RTC_NONE          },
  { .ClkMuxId = RCC_CLK_MUX_RTC_LSE           , .BlockId = RCC_BLOCK_RTCAPB   , .ClkMuxRegId = RCC_REG_BDCR     , .ClkSrcMask = RCC_BDCR_RTCSEL        , .ClkSrcVal = LL_RCC_RTC_CLKSOURCE_LSE          , .DefaultClkMuxId = RCC_CLK_MUX_RTC_NONE          },
  { .ClkMuxId = RCC_CLK_MUX_RTC_LSI           , .BlockId = RCC_BLOCK_RTCAPB   , .ClkMuxRegId = RCC_REG_BDCR     , .ClkSrcMask = RCC_BDCR_RTCSEL        , .ClkSrcVal = LL_RCC_RTC_CLKSOURCE_LSI          , .DefaultClkMuxId = RCC_CLK_MUX_RTC_NONE          },
#if defined(LL_RCC_USART16910_CLKSOURCE_PCLK2)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART16910_PCLK2      , RCC_BLOCK_USART1        , LL_RCC_USART16910_CLKSOURCE_PCLK2, RCC_CLK_MUX_USART16910_PCLK2 ),
#endif
#if defined(LL_RCC_USART16910_CLKSOURCE_PLL2Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART16910_PLL2Q      , RCC_BLOCK_USART1        , LL_RCC_USART16910_CLKSOURCE_PLL2Q, RCC_CLK_MUX_USART16910_PCLK2 ),
#endif
#if defined(LL_RCC_USART16910_CLKSOURCE_PLL3Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART16910_PLL3Q      , RCC_BLOCK_USART1        , LL_RCC_USART16910_CLKSOURCE_PLL3Q, RCC_CLK_MUX_USART16910_PCLK2 ),
#endif
#if defined(LL_RCC_USART16910_CLKSOURCE_HSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART16910_HSI        , RCC_BLOCK_USART1        , LL_RCC_USART16910_CLKSOURCE_HSI, RCC_CLK_MUX_USART16910_PCLK2 ),
#endif
#if defined(LL_RCC_USART16910_CLKSOURCE_CSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART16910_CSI        , RCC_BLOCK_USART1        , LL_RCC_USART16910_CLKSOURCE_CSI, RCC_CLK_MUX_USART16910_PCLK2 ),
#endif
#if defined(LL_RCC_USART16910_CLKSOURCE_LSE)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART16910_LSE        , RCC_BLOCK_USART1        , LL_RCC_USART16910_CLKSOURCE_LSE, RCC_CLK_MUX_USART16910_PCLK2 ),
#endif
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART234578_PCLK1     , RCC_BLOCK_USART2        , LL_RCC_USART234578_CLKSOURCE_PCLK1, RCC_CLK_MUX_USART234578_PCLK1 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART234578_PLL2Q     , RCC_BLOCK_USART2        , LL_RCC_USART234578_CLKSOURCE_PLL2Q, RCC_CLK_MUX_USART234578_PCLK1 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART234578_PLL3Q     , RCC_BLOCK_USART2        , LL_RCC_USART234578_CLKSOURCE_PLL3Q, RCC_CLK_MUX_USART234578_PCLK1 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART234578_HSI       , RCC_BLOCK_USART2        , LL_RCC_USART234578_CLKSOURCE_HSI, RCC_CLK_MUX_USART234578_PCLK1 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART234578_CSI       , RCC_BLOCK_USART2        , LL_RCC_USART234578_CLKSOURCE_CSI, RCC_CLK_MUX_USART234578_PCLK1 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART234578_LSE       , RCC_BLOCK_USART2        , LL_RCC_USART234578_CLKSOURCE_LSE, RCC_CLK_MUX_USART234578_PCLK1 ),
#if defined(RCC_D3CCIPR_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_PCLK4         , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( D3CCIP, RCC_D3CCIPR_LPUART1SEL, RCC_D3CCIPR_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_PCLK4 ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#elif defined(RCC_SRDCCIPR_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_PCLK4         , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( SRDCCIP, RCC_SRDCCIPR_LPUART1SEL, RCC_SRDCCIPR_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_PCLK4 ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#elif defined(RCC_CCIPR4_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_PCLK4         , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( CCIPR4_OFFSET, RCC_CCIPR4_LPUART1SEL, RCC_CCIPR4_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_PCLK4 ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#endif
#if defined(RCC_D3CCIPR_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_PLL2Q         , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( D3CCIP, RCC_D3CCIPR_LPUART1SEL, RCC_D3CCIPR_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_PLL2Q ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#elif defined(RCC_SRDCCIPR_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_PLL2Q         , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( SRDCCIP, RCC_SRDCCIPR_LPUART1SEL, RCC_SRDCCIPR_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_PLL2Q ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#elif defined(RCC_CCIPR4_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_PLL2Q         , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( CCIPR4_OFFSET, RCC_CCIPR4_LPUART1SEL, RCC_CCIPR4_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_PLL2Q ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#endif
#if defined(RCC_D3CCIPR_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_PLL3Q         , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( D3CCIP, RCC_D3CCIPR_LPUART1SEL, RCC_D3CCIPR_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_PLL3Q ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#elif defined(RCC_SRDCCIPR_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_PLL3Q         , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( SRDCCIP, RCC_SRDCCIPR_LPUART1SEL, RCC_SRDCCIPR_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_PLL3Q ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#elif defined(RCC_CCIPR4_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_PLL3Q         , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( CCIPR4_OFFSET, RCC_CCIPR4_LPUART1SEL, RCC_CCIPR4_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_PLL3Q ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#endif
#if defined(RCC_D3CCIPR_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_HSI           , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( D3CCIP, RCC_D3CCIPR_LPUART1SEL, RCC_D3CCIPR_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_HSI ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#elif defined(RCC_SRDCCIPR_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_HSI           , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( SRDCCIP, RCC_SRDCCIPR_LPUART1SEL, RCC_SRDCCIPR_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_HSI ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#elif defined(RCC_CCIPR4_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_HSI           , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( CCIPR4_OFFSET, RCC_CCIPR4_LPUART1SEL, RCC_CCIPR4_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_HSI ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#endif
#if defined(RCC_D3CCIPR_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_CSI           , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( D3CCIP, RCC_D3CCIPR_LPUART1SEL, RCC_D3CCIPR_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_CSI ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#elif defined(RCC_SRDCCIPR_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_CSI           , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( SRDCCIP, RCC_SRDCCIPR_LPUART1SEL, RCC_SRDCCIPR_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_CSI ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#elif defined(RCC_CCIPR4_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_CSI           , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( CCIPR4_OFFSET, RCC_CCIPR4_LPUART1SEL, RCC_CCIPR4_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_CSI ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#endif
#if defined(RCC_D3CCIPR_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_LSE           , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( D3CCIP, RCC_D3CCIPR_LPUART1SEL, RCC_D3CCIPR_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_LSE ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#elif defined(RCC_SRDCCIPR_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_LSE           , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( SRDCCIP, RCC_SRDCCIPR_LPUART1SEL, RCC_SRDCCIPR_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_LSE ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#elif defined(RCC_CCIPR4_LPUART1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPUART1_LSE           , RCC_BLOCK_LPUART1       , LL_CLKSOURCE( CCIPR4_OFFSET, RCC_CCIPR4_LPUART1SEL, RCC_CCIPR4_LPUART1SEL_Pos, LL_RCC_LPUART1_CLKSOURCE_LSE ), RCC_CLK_MUX_LPUART1_PCLK4 ),
#endif
#if defined(LL_RCC_SPI123_CLKSOURCE_PLL1Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI123_PLL1Q          , RCC_BLOCK_SPI1          , LL_RCC_SPI123_CLKSOURCE_PLL1Q, RCC_CLK_MUX_SPI123_PLL1Q ),
#endif
#if defined(LL_RCC_SPI123_CLKSOURCE_PLL2P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI123_PLL2P          , RCC_BLOCK_SPI1          , LL_RCC_SPI123_CLKSOURCE_PLL2P, RCC_CLK_MUX_SPI123_PLL1Q ),
#endif
#if defined(LL_RCC_SPI123_CLKSOURCE_PLL3P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI123_PLL3P          , RCC_BLOCK_SPI1          , LL_RCC_SPI123_CLKSOURCE_PLL3P, RCC_CLK_MUX_SPI123_PLL1Q ),
#endif
#if defined(LL_RCC_SPI123_CLKSOURCE_I2S_CKIN)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI123_PIN            , RCC_BLOCK_SPI1          , LL_RCC_SPI123_CLKSOURCE_I2S_CKIN, RCC_CLK_MUX_SPI123_PLL1Q ),
#endif
#if defined(LL_RCC_SPI123_CLKSOURCE_CLKP)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI123_LPCLK          , RCC_BLOCK_SPI1          , LL_RCC_SPI123_CLKSOURCE_CLKP, RCC_CLK_MUX_SPI123_PLL1Q ),
#endif
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI45_PCLK2           , RCC_BLOCK_SPI4          , LL_RCC_SPI45_CLKSOURCE_PCLK2, RCC_CLK_MUX_SPI45_PCLK2 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI45_PLL2Q           , RCC_BLOCK_SPI4          , LL_RCC_SPI45_CLKSOURCE_PLL2Q, RCC_CLK_MUX_SPI45_PCLK2 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI45_PLL3Q           , RCC_BLOCK_SPI4          , LL_RCC_SPI45_CLKSOURCE_PLL3Q, RCC_CLK_MUX_SPI45_PCLK2 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI45_HSI             , RCC_BLOCK_SPI4          , LL_RCC_SPI45_CLKSOURCE_HSI, RCC_CLK_MUX_SPI45_PCLK2 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI45_CSI             , RCC_BLOCK_SPI4          , LL_RCC_SPI45_CLKSOURCE_CSI, RCC_CLK_MUX_SPI45_PCLK2 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI45_HSE             , RCC_BLOCK_SPI4          , LL_RCC_SPI45_CLKSOURCE_HSE, RCC_CLK_MUX_SPI45_PCLK2 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI6_PCLK4            , RCC_BLOCK_SPI6          , LL_RCC_SPI6_CLKSOURCE_PCLK4, RCC_CLK_MUX_SPI6_PCLK4 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI6_PLL2Q            , RCC_BLOCK_SPI6          , LL_RCC_SPI6_CLKSOURCE_PLL2Q, RCC_CLK_MUX_SPI6_PCLK4 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI6_PLL3Q            , RCC_BLOCK_SPI6          , LL_RCC_SPI6_CLKSOURCE_PLL3Q, RCC_CLK_MUX_SPI6_PCLK4 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI6_HSI              , RCC_BLOCK_SPI6          , LL_RCC_SPI6_CLKSOURCE_HSI, RCC_CLK_MUX_SPI6_PCLK4 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI6_CSI              , RCC_BLOCK_SPI6          , LL_RCC_SPI6_CLKSOURCE_CSI, RCC_CLK_MUX_SPI6_PCLK4 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI6_HSE              , RCC_BLOCK_SPI6          , LL_RCC_SPI6_CLKSOURCE_HSE, RCC_CLK_MUX_SPI6_PCLK4 ),
#if defined(LL_RCC_SPI6_CLKSOURCE_I2S_CKIN)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI6_PIN              , RCC_BLOCK_SPI6          , LL_RCC_SPI6_CLKSOURCE_I2S_CKIN, RCC_CLK_MUX_SPI6_PCLK4 ),
#endif
#if defined(LL_RCC_I2C123_CLKSOURCE_PCLK1)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C123_PCLK1          , RCC_BLOCK_I2C1          , LL_RCC_I2C123_CLKSOURCE_PCLK1, RCC_CLK_MUX_I2C123_PCLK1 ),
#endif
#if defined(LL_RCC_I2C123_CLKSOURCE_PLL3R)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C123_PLL3R          , RCC_BLOCK_I2C1          , LL_RCC_I2C123_CLKSOURCE_PLL3R, RCC_CLK_MUX_I2C123_PCLK1 ),
#endif
#if defined(LL_RCC_I2C123_CLKSOURCE_HSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C123_HSI            , RCC_BLOCK_I2C1          , LL_RCC_I2C123_CLKSOURCE_HSI, RCC_CLK_MUX_I2C123_PCLK1 ),
#endif
#if defined(LL_RCC_I2C123_CLKSOURCE_CSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C123_CSI            , RCC_BLOCK_I2C1          , LL_RCC_I2C123_CLKSOURCE_CSI, RCC_CLK_MUX_I2C123_PCLK1 ),
#endif
#if defined(LL_RCC_I2C4_CLKSOURCE_PCLK4)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C4_PCLK4            , RCC_BLOCK_I2C4          , LL_RCC_I2C4_CLKSOURCE_PCLK4, RCC_CLK_MUX_I2C4_PCLK4 ),
#endif
#if defined(LL_RCC_I2C4_CLKSOURCE_PLL3R)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C4_PLL3R            , RCC_BLOCK_I2C4          , LL_RCC_I2C4_CLKSOURCE_PLL3R, RCC_CLK_MUX_I2C4_PCLK4 ),
#endif
#if defined(LL_RCC_I2C4_CLKSOURCE_HSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C4_HSI              , RCC_BLOCK_I2C4          , LL_RCC_I2C4_CLKSOURCE_HSI, RCC_CLK_MUX_I2C4_PCLK4 ),
#endif
#if defined(LL_RCC_I2C4_CLKSOURCE_CSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C4_CSI              , RCC_BLOCK_I2C4          , LL_RCC_I2C4_CLKSOURCE_CSI, RCC_CLK_MUX_I2C4_PCLK4 ),
#endif
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM1_PCLK1          , RCC_BLOCK_LPTIM1        , LL_RCC_LPTIM1_CLKSOURCE_PCLK1, RCC_CLK_MUX_LPTIM1_PCLK1 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM1_PLL2P          , RCC_BLOCK_LPTIM1        , LL_RCC_LPTIM1_CLKSOURCE_PLL2P, RCC_CLK_MUX_LPTIM1_PCLK1 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM1_PLL3R          , RCC_BLOCK_LPTIM1        , LL_RCC_LPTIM1_CLKSOURCE_PLL3R, RCC_CLK_MUX_LPTIM1_PCLK1 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM1_LSE            , RCC_BLOCK_LPTIM1        , LL_RCC_LPTIM1_CLKSOURCE_LSE, RCC_CLK_MUX_LPTIM1_PCLK1 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM1_LSI            , RCC_BLOCK_LPTIM1        , LL_RCC_LPTIM1_CLKSOURCE_LSI, RCC_CLK_MUX_LPTIM1_PCLK1 ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM1_LPCLK          , RCC_BLOCK_LPTIM1        , LL_RCC_LPTIM1_CLKSOURCE_CLKP, RCC_CLK_MUX_LPTIM1_PCLK1 ),
#if defined(LL_RCC_LPTIM2_CLKSOURCE_PCLK4)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM2_PCLK4          , RCC_BLOCK_LPTIM2        , LL_RCC_LPTIM2_CLKSOURCE_PCLK4, RCC_CLK_MUX_LPTIM2_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM2_CLKSOURCE_PLL2P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM2_PLL2P          , RCC_BLOCK_LPTIM2        , LL_RCC_LPTIM2_CLKSOURCE_PLL2P, RCC_CLK_MUX_LPTIM2_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM2_CLKSOURCE_PLL3R)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM2_PLL3R          , RCC_BLOCK_LPTIM2        , LL_RCC_LPTIM2_CLKSOURCE_PLL3R, RCC_CLK_MUX_LPTIM2_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM2_CLKSOURCE_LSE)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM2_LSE            , RCC_BLOCK_LPTIM2        , LL_RCC_LPTIM2_CLKSOURCE_LSE, RCC_CLK_MUX_LPTIM2_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM2_CLKSOURCE_LSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM2_LSI            , RCC_BLOCK_LPTIM2        , LL_RCC_LPTIM2_CLKSOURCE_LSI, RCC_CLK_MUX_LPTIM2_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM2_CLKSOURCE_CLKP)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM2_LPCLK          , RCC_BLOCK_LPTIM2        , LL_RCC_LPTIM2_CLKSOURCE_CLKP, RCC_CLK_MUX_LPTIM2_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM345_CLKSOURCE_PCLK4)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM345_PCLK4        , RCC_BLOCK_LPTIM3        , LL_RCC_LPTIM345_CLKSOURCE_PCLK4, RCC_CLK_MUX_LPTIM345_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM345_CLKSOURCE_PLL2P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM345_PLL2P        , RCC_BLOCK_LPTIM3        , LL_RCC_LPTIM345_CLKSOURCE_PLL2P, RCC_CLK_MUX_LPTIM345_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM345_CLKSOURCE_PLL3R)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM345_PLL3R        , RCC_BLOCK_LPTIM3        , LL_RCC_LPTIM345_CLKSOURCE_PLL3R, RCC_CLK_MUX_LPTIM345_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM345_CLKSOURCE_LSE)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM345_LSE          , RCC_BLOCK_LPTIM3        , LL_RCC_LPTIM345_CLKSOURCE_LSE, RCC_CLK_MUX_LPTIM345_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM345_CLKSOURCE_LSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM345_LSI          , RCC_BLOCK_LPTIM3        , LL_RCC_LPTIM345_CLKSOURCE_LSI, RCC_CLK_MUX_LPTIM345_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM345_CLKSOURCE_CLKP)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM345_LPCLK        , RCC_BLOCK_LPTIM3        , LL_RCC_LPTIM345_CLKSOURCE_CLKP, RCC_CLK_MUX_LPTIM345_PCLK4 ),
#endif
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI1_PLL1Q            , RCC_BLOCK_SAI1          , LL_RCC_SAI1_CLKSOURCE_PLL1Q, RCC_CLK_MUX_SAI1_PLL1Q ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI1_PLL2P            , RCC_BLOCK_SAI1          , LL_RCC_SAI1_CLKSOURCE_PLL2P, RCC_CLK_MUX_SAI1_PLL1Q ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI1_PLL3P            , RCC_BLOCK_SAI1          , LL_RCC_SAI1_CLKSOURCE_PLL3P, RCC_CLK_MUX_SAI1_PLL1Q ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI1_PIN              , RCC_BLOCK_SAI1          , LL_RCC_SAI1_CLKSOURCE_I2S_CKIN, RCC_CLK_MUX_SAI1_PLL1Q ),
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI1_LPCLK            , RCC_BLOCK_SAI1          , LL_RCC_SAI1_CLKSOURCE_CLKP, RCC_CLK_MUX_SAI1_PLL1Q ),
#if defined(LL_RCC_SAI23_CLKSOURCE_PLL1Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI23_PLL1Q           , RCC_BLOCK_SAI2          , LL_RCC_SAI23_CLKSOURCE_PLL1Q, RCC_CLK_MUX_SAI23_PLL1Q ),
#endif
#if defined(LL_RCC_SAI23_CLKSOURCE_PLL2P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI23_PLL2P           , RCC_BLOCK_SAI2          , LL_RCC_SAI23_CLKSOURCE_PLL2P, RCC_CLK_MUX_SAI23_PLL1Q ),
#endif
#if defined(LL_RCC_SAI23_CLKSOURCE_PLL3P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI23_PLL3P           , RCC_BLOCK_SAI2          , LL_RCC_SAI23_CLKSOURCE_PLL3P, RCC_CLK_MUX_SAI23_PLL1Q ),
#endif
#if defined(LL_RCC_SAI23_CLKSOURCE_I2S_CKIN)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI23_PIN             , RCC_BLOCK_SAI2          , LL_RCC_SAI23_CLKSOURCE_I2S_CKIN, RCC_CLK_MUX_SAI23_PLL1Q ),
#endif
#if defined(LL_RCC_SAI23_CLKSOURCE_CLKP)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI23_LPCLK           , RCC_BLOCK_SAI2          , LL_RCC_SAI23_CLKSOURCE_CLKP, RCC_CLK_MUX_SAI23_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2A_CLKSOURCE_PLL1Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2A_PLL1Q           , RCC_BLOCK_SAI2          , LL_RCC_SAI2A_CLKSOURCE_PLL1Q, RCC_CLK_MUX_SAI2A_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2A_CLKSOURCE_PLL2P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2A_PLL2P           , RCC_BLOCK_SAI2          , LL_RCC_SAI2A_CLKSOURCE_PLL2P, RCC_CLK_MUX_SAI2A_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2A_CLKSOURCE_PLL3P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2A_PLL3P           , RCC_BLOCK_SAI2          , LL_RCC_SAI2A_CLKSOURCE_PLL3P, RCC_CLK_MUX_SAI2A_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2A_CLKSOURCE_I2S_CKIN)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2A_PIN             , RCC_BLOCK_SAI2          , LL_RCC_SAI2A_CLKSOURCE_I2S_CKIN, RCC_CLK_MUX_SAI2A_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2A_CLKSOURCE_CLKP)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2A_LPCLK           , RCC_BLOCK_SAI2          , LL_RCC_SAI2A_CLKSOURCE_CLKP, RCC_CLK_MUX_SAI2A_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2A_CLKSOURCE_SPDIF)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2A_SPDIF           , RCC_BLOCK_SAI2          , LL_RCC_SAI2A_CLKSOURCE_SPDIF, RCC_CLK_MUX_SAI2A_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2B_CLKSOURCE_PLL1Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2B_PLL1Q           , RCC_BLOCK_SAI2          , LL_RCC_SAI2B_CLKSOURCE_PLL1Q, RCC_CLK_MUX_SAI2B_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2B_CLKSOURCE_PLL2P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2B_PLL2P           , RCC_BLOCK_SAI2          , LL_RCC_SAI2B_CLKSOURCE_PLL2P, RCC_CLK_MUX_SAI2B_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2B_CLKSOURCE_PLL3P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2B_PLL3P           , RCC_BLOCK_SAI2          , LL_RCC_SAI2B_CLKSOURCE_PLL3P, RCC_CLK_MUX_SAI2B_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2B_CLKSOURCE_I2S_CKIN)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2B_PIN             , RCC_BLOCK_SAI2          , LL_RCC_SAI2B_CLKSOURCE_I2S_CKIN, RCC_CLK_MUX_SAI2B_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2B_CLKSOURCE_CLKP)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2B_LPCLK           , RCC_BLOCK_SAI2          , LL_RCC_SAI2B_CLKSOURCE_CLKP, RCC_CLK_MUX_SAI2B_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2B_CLKSOURCE_SPDIF)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2B_SPDIF           , RCC_BLOCK_SAI2          , LL_RCC_SAI2B_CLKSOURCE_SPDIF, RCC_CLK_MUX_SAI2B_PLL1Q ),
#endif
#if defined(LL_RCC_SAI4A_CLKSOURCE_PLL1Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI4A_PLL1Q           , RCC_BLOCK_SAI4          , LL_RCC_SAI4A_CLKSOURCE_PLL1Q, RCC_CLK_MUX_SAI4A_PLL1Q ),
#endif
#if defined(LL_RCC_SAI4A_CLKSOURCE_PLL2P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI4A_PLL2P           , RCC_BLOCK_SAI4          , LL_RCC_SAI4A_CLKSOURCE_PLL2P, RCC_CLK_MUX_SAI4A_PLL1Q ),
#endif
#if defined(LL_RCC_SAI4A_CLKSOURCE_PLL3P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI4A_PLL3P           , RCC_BLOCK_SAI4          , LL_RCC_SAI4A_CLKSOURCE_PLL3P, RCC_CLK_MUX_SAI4A_PLL1Q ),
#endif
#if defined(LL_RCC_SAI4A_CLKSOURCE_I2S_CKIN)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI4A_PIN             , RCC_BLOCK_SAI4          , LL_RCC_SAI4A_CLKSOURCE_I2S_CKIN, RCC_CLK_MUX_SAI4A_PLL1Q ),
#endif
#if defined(LL_RCC_SAI4A_CLKSOURCE_CLKP)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI4A_LPCLK           , RCC_BLOCK_SAI4          , LL_RCC_SAI4A_CLKSOURCE_CLKP, RCC_CLK_MUX_SAI4A_PLL1Q ),
#endif
#if defined(LL_RCC_SAI4A_CLKSOURCE_SPDIF)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI4A_SPDIF           , RCC_BLOCK_SAI4          , LL_RCC_SAI4A_CLKSOURCE_SPDIF, RCC_CLK_MUX_SAI4A_PLL1Q ),
#endif
#if defined(LL_RCC_SAI4B_CLKSOURCE_PLL1Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI4B_PLL1Q           , RCC_BLOCK_SAI4          , LL_RCC_SAI4B_CLKSOURCE_PLL1Q, RCC_CLK_MUX_SAI4B_PLL1Q ),
#endif
#if defined(LL_RCC_SAI4B_CLKSOURCE_PLL2P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI4B_PLL2P           , RCC_BLOCK_SAI4          , LL_RCC_SAI4B_CLKSOURCE_PLL2P, RCC_CLK_MUX_SAI4B_PLL1Q ),
#endif
#if defined(LL_RCC_SAI4B_CLKSOURCE_PLL3P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI4B_PLL3P           , RCC_BLOCK_SAI4          , LL_RCC_SAI4B_CLKSOURCE_PLL3P, RCC_CLK_MUX_SAI4B_PLL1Q ),
#endif
#if defined(LL_RCC_SAI4B_CLKSOURCE_I2S_CKIN)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI4B_PIN             , RCC_BLOCK_SAI4          , LL_RCC_SAI4B_CLKSOURCE_I2S_CKIN, RCC_CLK_MUX_SAI4B_PLL1Q ),
#endif
#if defined(LL_RCC_SAI4B_CLKSOURCE_CLKP)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI4B_LPCLK           , RCC_BLOCK_SAI4          , LL_RCC_SAI4B_CLKSOURCE_CLKP, RCC_CLK_MUX_SAI4B_PLL1Q ),
#endif
#if defined(LL_RCC_SAI4B_CLKSOURCE_SPDIF)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI4B_SPDIF           , RCC_BLOCK_SAI4          , LL_RCC_SAI4B_CLKSOURCE_SPDIF, RCC_CLK_MUX_SAI4B_PLL1Q ),
#endif
#if defined(LL_RCC_SPDIF_CLKSOURCE_PLL1Q)
#if defined(RCC_D2CCIP1R_SPDIFSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPDIF_PLL1Q           , RCC_BLOCK_SPDIFRX       , LL_CLKSOURCE( D2CCIP1, RCC_D2CCIP1R_SPDIFSEL, RCC_D2CCIP1R_SPDIFSEL_Pos, LL_RCC_SPDIF_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_SPDIF_PLL1Q ),
#elif defined(RCC_CDCCIP1R_SPDIFSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPDIF_PLL1Q           , RCC_BLOCK_SPDIFRX       , LL_CLKSOURCE( CDCCIP1, RCC_CDCCIP1R_SPDIFSEL, RCC_CDCCIP1R_SPDIFSEL_Pos, LL_RCC_SPDIF_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_SPDIF_PLL1Q ),
#endif
#endif
#if defined(LL_RCC_SPDIF_CLKSOURCE_PLL2R)
#if defined(RCC_D2CCIP1R_SPDIFSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPDIF_PLL2R           , RCC_BLOCK_SPDIFRX       , LL_CLKSOURCE( D2CCIP1, RCC_D2CCIP1R_SPDIFSEL, RCC_D2CCIP1R_SPDIFSEL_Pos, LL_RCC_SPDIF_CLKSOURCE_PLL2R ), RCC_CLK_MUX_SPDIF_PLL1Q ),
#elif defined(RCC_CDCCIP1R_SPDIFSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPDIF_PLL2R           , RCC_BLOCK_SPDIFRX       , LL_CLKSOURCE( CDCCIP1, RCC_CDCCIP1R_SPDIFSEL, RCC_CDCCIP1R_SPDIFSEL_Pos, LL_RCC_SPDIF_CLKSOURCE_PLL2R ), RCC_CLK_MUX_SPDIF_PLL1Q ),
#endif
#endif
#if defined(LL_RCC_SPDIF_CLKSOURCE_PLL3R)
#if defined(RCC_D2CCIP1R_SPDIFSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPDIF_PLL3R           , RCC_BLOCK_SPDIFRX       , LL_CLKSOURCE( D2CCIP1, RCC_D2CCIP1R_SPDIFSEL, RCC_D2CCIP1R_SPDIFSEL_Pos, LL_RCC_SPDIF_CLKSOURCE_PLL3R ), RCC_CLK_MUX_SPDIF_PLL1Q ),
#elif defined(RCC_CDCCIP1R_SPDIFSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPDIF_PLL3R           , RCC_BLOCK_SPDIFRX       , LL_CLKSOURCE( CDCCIP1, RCC_CDCCIP1R_SPDIFSEL, RCC_CDCCIP1R_SPDIFSEL_Pos, LL_RCC_SPDIF_CLKSOURCE_PLL3R ), RCC_CLK_MUX_SPDIF_PLL1Q ),
#endif
#endif
#if defined(LL_RCC_SPDIF_CLKSOURCE_HSI)
#if defined(RCC_D2CCIP1R_SPDIFSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPDIF_HSI             , RCC_BLOCK_SPDIFRX       , LL_CLKSOURCE( D2CCIP1, RCC_D2CCIP1R_SPDIFSEL, RCC_D2CCIP1R_SPDIFSEL_Pos, LL_RCC_SPDIF_CLKSOURCE_HSI ), RCC_CLK_MUX_SPDIF_PLL1Q ),
#elif defined(RCC_CDCCIP1R_SPDIFSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPDIF_HSI             , RCC_BLOCK_SPDIFRX       , LL_CLKSOURCE( CDCCIP1, RCC_CDCCIP1R_SPDIFSEL, RCC_CDCCIP1R_SPDIFSEL_Pos, LL_RCC_SPDIF_CLKSOURCE_HSI ), RCC_CLK_MUX_SPDIF_PLL1Q ),
#endif
#endif
#if defined(LL_RCC_RNG_CLKSOURCE_HSI48)
#if defined(RCC_D2CCIP2R_RNGSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_RNG_HSI48             , RCC_BLOCK_RNG           , LL_CLKSOURCE( D2CCIP2, RCC_D2CCIP2R_RNGSEL, RCC_D2CCIP2R_RNGSEL_Pos, LL_RCC_RNG_CLKSOURCE_HSI48 ), RCC_CLK_MUX_RNG_HSI48 ),
#elif defined(RCC_CDCCIP2R_RNGSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_RNG_HSI48             , RCC_BLOCK_RNG           , LL_CLKSOURCE( CDCCIP2, RCC_CDCCIP2R_RNGSEL, RCC_CDCCIP2R_RNGSEL_Pos, LL_RCC_RNG_CLKSOURCE_HSI48 ), RCC_CLK_MUX_RNG_HSI48 ),
#endif
#endif
#if defined(LL_RCC_RNG_CLKSOURCE_PLL1Q)
#if defined(RCC_D2CCIP2R_RNGSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_RNG_PLL1Q             , RCC_BLOCK_RNG           , LL_CLKSOURCE( D2CCIP2, RCC_D2CCIP2R_RNGSEL, RCC_D2CCIP2R_RNGSEL_Pos, LL_RCC_RNG_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_RNG_HSI48 ),
#elif defined(RCC_CDCCIP2R_RNGSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_RNG_PLL1Q             , RCC_BLOCK_RNG           , LL_CLKSOURCE( CDCCIP2, RCC_CDCCIP2R_RNGSEL, RCC_CDCCIP2R_RNGSEL_Pos, LL_RCC_RNG_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_RNG_HSI48 ),
#endif
#endif
#if defined(LL_RCC_RNG_CLKSOURCE_LSE)
#if defined(RCC_D2CCIP2R_RNGSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_RNG_LSE               , RCC_BLOCK_RNG           , LL_CLKSOURCE( D2CCIP2, RCC_D2CCIP2R_RNGSEL, RCC_D2CCIP2R_RNGSEL_Pos, LL_RCC_RNG_CLKSOURCE_LSE ), RCC_CLK_MUX_RNG_HSI48 ),
#elif defined(RCC_CDCCIP2R_RNGSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_RNG_LSE               , RCC_BLOCK_RNG           , LL_CLKSOURCE( CDCCIP2, RCC_CDCCIP2R_RNGSEL, RCC_CDCCIP2R_RNGSEL_Pos, LL_RCC_RNG_CLKSOURCE_LSE ), RCC_CLK_MUX_RNG_HSI48 ),
#endif
#endif
#if defined(LL_RCC_RNG_CLKSOURCE_LSI)
#if defined(RCC_D2CCIP2R_RNGSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_RNG_LSI               , RCC_BLOCK_RNG           , LL_CLKSOURCE( D2CCIP2, RCC_D2CCIP2R_RNGSEL, RCC_D2CCIP2R_RNGSEL_Pos, LL_RCC_RNG_CLKSOURCE_LSI ), RCC_CLK_MUX_RNG_HSI48 ),
#elif defined(RCC_CDCCIP2R_RNGSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_RNG_LSI               , RCC_BLOCK_RNG           , LL_CLKSOURCE( CDCCIP2, RCC_CDCCIP2R_RNGSEL, RCC_CDCCIP2R_RNGSEL_Pos, LL_RCC_RNG_CLKSOURCE_LSI ), RCC_CLK_MUX_RNG_HSI48 ),
#endif
#endif
#if defined(LL_RCC_USB_CLKSOURCE_DISABLE)
#if defined(RCC_D2CCIP2R_USBSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USB_DISABLE           , RCC_BLOCK_USB1OTGHS     , LL_CLKSOURCE( D2CCIP2, RCC_D2CCIP2R_USBSEL, RCC_D2CCIP2R_USBSEL_Pos, LL_RCC_USB_CLKSOURCE_DISABLE ), RCC_CLK_MUX_USB_DISABLE ),
#elif defined(RCC_CDCCIP2R_USBSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USB_DISABLE           , RCC_BLOCK_USB1OTGHS     , LL_CLKSOURCE( CDCCIP2, RCC_CDCCIP2R_USBSEL, RCC_CDCCIP2R_USBSEL_Pos, LL_RCC_USB_CLKSOURCE_DISABLE ), RCC_CLK_MUX_USB_DISABLE ),
#endif
#endif
#if defined(LL_RCC_USB_CLKSOURCE_PLL1Q)
#if defined(RCC_D2CCIP2R_USBSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USB_PLL1Q             , RCC_BLOCK_USB1OTGHS     , LL_CLKSOURCE( D2CCIP2, RCC_D2CCIP2R_USBSEL, RCC_D2CCIP2R_USBSEL_Pos, LL_RCC_USB_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_USB_DISABLE ),
#elif defined(RCC_CDCCIP2R_USBSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USB_PLL1Q             , RCC_BLOCK_USB1OTGHS     , LL_CLKSOURCE( CDCCIP2, RCC_CDCCIP2R_USBSEL, RCC_CDCCIP2R_USBSEL_Pos, LL_RCC_USB_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_USB_DISABLE ),
#endif
#endif
#if defined(LL_RCC_USB_CLKSOURCE_PLL3Q)
#if defined(RCC_D2CCIP2R_USBSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USB_PLL3Q             , RCC_BLOCK_USB1OTGHS     , LL_CLKSOURCE( D2CCIP2, RCC_D2CCIP2R_USBSEL, RCC_D2CCIP2R_USBSEL_Pos, LL_RCC_USB_CLKSOURCE_PLL3Q ), RCC_CLK_MUX_USB_DISABLE ),
#elif defined(RCC_CDCCIP2R_USBSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USB_PLL3Q             , RCC_BLOCK_USB1OTGHS     , LL_CLKSOURCE( CDCCIP2, RCC_CDCCIP2R_USBSEL, RCC_CDCCIP2R_USBSEL_Pos, LL_RCC_USB_CLKSOURCE_PLL3Q ), RCC_CLK_MUX_USB_DISABLE ),
#endif
#endif
#if defined(LL_RCC_USB_CLKSOURCE_HSI48)
#if defined(RCC_D2CCIP2R_USBSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USB_HSI48             , RCC_BLOCK_USB1OTGHS     , LL_CLKSOURCE( D2CCIP2, RCC_D2CCIP2R_USBSEL, RCC_D2CCIP2R_USBSEL_Pos, LL_RCC_USB_CLKSOURCE_HSI48 ), RCC_CLK_MUX_USB_DISABLE ),
#elif defined(RCC_CDCCIP2R_USBSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USB_HSI48             , RCC_BLOCK_USB1OTGHS     , LL_CLKSOURCE( CDCCIP2, RCC_CDCCIP2R_USBSEL, RCC_CDCCIP2R_USBSEL_Pos, LL_RCC_USB_CLKSOURCE_HSI48 ), RCC_CLK_MUX_USB_DISABLE ),
#endif
#endif
#if defined(RCC_D2CCIP1R_FDCANSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FDCAN_HSE             , RCC_BLOCK_FDCAN         , LL_CLKSOURCE( D2CCIP1, RCC_D2CCIP1R_FDCANSEL, RCC_D2CCIP1R_FDCANSEL_Pos, LL_RCC_FDCAN_CLKSOURCE_HSE ), RCC_CLK_MUX_FDCAN_HSE ),
#elif defined(RCC_CDCCIP1R_FDCANSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FDCAN_HSE             , RCC_BLOCK_FDCAN         , LL_CLKSOURCE( CDCCIP1, RCC_CDCCIP1R_FDCANSEL, RCC_CDCCIP1R_FDCANSEL_Pos, LL_RCC_FDCAN_CLKSOURCE_HSE ), RCC_CLK_MUX_FDCAN_HSE ),
#elif defined(RCC_CCIPR2_FDCANSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FDCAN_HSE             , RCC_BLOCK_FDCAN         , LL_CLKSOURCE( CCIPR2_OFFSET, RCC_CCIPR2_FDCANSEL, RCC_CCIPR2_FDCANSEL_Pos, LL_RCC_FDCAN_CLKSOURCE_HSE ), RCC_CLK_MUX_FDCAN_HSE ),
#endif
#if defined(RCC_D2CCIP1R_FDCANSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FDCAN_PLL1Q           , RCC_BLOCK_FDCAN         , LL_CLKSOURCE( D2CCIP1, RCC_D2CCIP1R_FDCANSEL, RCC_D2CCIP1R_FDCANSEL_Pos, LL_RCC_FDCAN_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_FDCAN_HSE ),
#elif defined(RCC_CDCCIP1R_FDCANSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FDCAN_PLL1Q           , RCC_BLOCK_FDCAN         , LL_CLKSOURCE( CDCCIP1, RCC_CDCCIP1R_FDCANSEL, RCC_CDCCIP1R_FDCANSEL_Pos, LL_RCC_FDCAN_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_FDCAN_HSE ),
#elif defined(RCC_CCIPR2_FDCANSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FDCAN_PLL1Q           , RCC_BLOCK_FDCAN         , LL_CLKSOURCE( CCIPR2_OFFSET, RCC_CCIPR2_FDCANSEL, RCC_CCIPR2_FDCANSEL_Pos, LL_RCC_FDCAN_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_FDCAN_HSE ),
#endif
#if defined(RCC_D2CCIP1R_FDCANSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FDCAN_PLL2Q           , RCC_BLOCK_FDCAN         , LL_CLKSOURCE( D2CCIP1, RCC_D2CCIP1R_FDCANSEL, RCC_D2CCIP1R_FDCANSEL_Pos, LL_RCC_FDCAN_CLKSOURCE_PLL2Q ), RCC_CLK_MUX_FDCAN_HSE ),
#elif defined(RCC_CDCCIP1R_FDCANSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FDCAN_PLL2Q           , RCC_BLOCK_FDCAN         , LL_CLKSOURCE( CDCCIP1, RCC_CDCCIP1R_FDCANSEL, RCC_CDCCIP1R_FDCANSEL_Pos, LL_RCC_FDCAN_CLKSOURCE_PLL2Q ), RCC_CLK_MUX_FDCAN_HSE ),
#elif defined(RCC_CCIPR2_FDCANSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FDCAN_PLL2Q           , RCC_BLOCK_FDCAN         , LL_CLKSOURCE( CCIPR2_OFFSET, RCC_CCIPR2_FDCANSEL, RCC_CCIPR2_FDCANSEL_Pos, LL_RCC_FDCAN_CLKSOURCE_PLL2Q ), RCC_CLK_MUX_FDCAN_HSE ),
#endif
#if defined(LL_RCC_SDMMC_CLKSOURCE_PLL1Q)
#if defined(RCC_D1CCIPR_SDMMCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SDMMC_PLL1Q           , RCC_BLOCK_SDMMC1        , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_SDMMCSEL, RCC_D1CCIPR_SDMMCSEL_Pos, LL_RCC_SDMMC_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_SDMMC_PLL1Q ),
#elif defined(RCC_CDCCIPR_SDMMCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SDMMC_PLL1Q           , RCC_BLOCK_SDMMC1        , LL_CLKSOURCE( CDCCIP, RCC_CDCCIPR_SDMMCSEL, RCC_CDCCIPR_SDMMCSEL_Pos, LL_RCC_SDMMC_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_SDMMC_PLL1Q ),
#endif
#endif
#if defined(LL_RCC_SDMMC_CLKSOURCE_PLL2R)
#if defined(RCC_D1CCIPR_SDMMCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SDMMC_PLL2R           , RCC_BLOCK_SDMMC1        , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_SDMMCSEL, RCC_D1CCIPR_SDMMCSEL_Pos, LL_RCC_SDMMC_CLKSOURCE_PLL2R ), RCC_CLK_MUX_SDMMC_PLL1Q ),
#elif defined(RCC_CDCCIPR_SDMMCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SDMMC_PLL2R           , RCC_BLOCK_SDMMC1        , LL_CLKSOURCE( CDCCIP, RCC_CDCCIPR_SDMMCSEL, RCC_CDCCIPR_SDMMCSEL_Pos, LL_RCC_SDMMC_CLKSOURCE_PLL2R ), RCC_CLK_MUX_SDMMC_PLL1Q ),
#endif
#endif
#if defined(LL_RCC_SDMMC_CLKSOURCE_PLL2S)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SDMMC_PLL2S           , RCC_BLOCK_SDMMC1        , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_SDMMC12SEL, RCC_CCIPR1_SDMMC12SEL_Pos, LL_RCC_SDMMC_CLKSOURCE_PLL2S ), RCC_CLK_MUX_SDMMC_PLL2S ),
#endif
#if defined(LL_RCC_SDMMC_CLKSOURCE_PLL2T)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SDMMC_PLL2T           , RCC_BLOCK_SDMMC1        , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_SDMMC12SEL, RCC_CCIPR1_SDMMC12SEL_Pos, LL_RCC_SDMMC_CLKSOURCE_PLL2T ), RCC_CLK_MUX_SDMMC_PLL2S ),
#endif
#if defined(RCC_D1CCIPR_FMCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FMC_HCLK              , RCC_BLOCK_FMC           , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_FMCSEL, RCC_D1CCIPR_FMCSEL_Pos, LL_RCC_FMC_CLKSOURCE_HCLK ), RCC_CLK_MUX_FMC_HCLK ),
#elif defined(RCC_CDCCIPR_FMCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FMC_HCLK              , RCC_BLOCK_FMC           , LL_CLKSOURCE( CDCCIP, RCC_CDCCIPR_FMCSEL, RCC_CDCCIPR_FMCSEL_Pos, LL_RCC_FMC_CLKSOURCE_HCLK ), RCC_CLK_MUX_FMC_HCLK ),
#elif defined(RCC_CCIPR1_FMCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FMC_HCLK              , RCC_BLOCK_FMC           , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_FMCSEL, RCC_CCIPR1_FMCSEL_Pos, LL_RCC_FMC_CLKSOURCE_HCLK ), RCC_CLK_MUX_FMC_HCLK ),
#endif
#if defined(RCC_D1CCIPR_FMCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FMC_PLL1Q             , RCC_BLOCK_FMC           , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_FMCSEL, RCC_D1CCIPR_FMCSEL_Pos, LL_RCC_FMC_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_FMC_HCLK ),
#elif defined(RCC_CDCCIPR_FMCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FMC_PLL1Q             , RCC_BLOCK_FMC           , LL_CLKSOURCE( CDCCIP, RCC_CDCCIPR_FMCSEL, RCC_CDCCIPR_FMCSEL_Pos, LL_RCC_FMC_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_FMC_HCLK ),
#elif defined(RCC_CCIPR1_FMCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FMC_PLL1Q             , RCC_BLOCK_FMC           , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_FMCSEL, RCC_CCIPR1_FMCSEL_Pos, LL_RCC_FMC_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_FMC_HCLK ),
#endif
#if defined(RCC_D1CCIPR_FMCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FMC_PLL2R             , RCC_BLOCK_FMC           , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_FMCSEL, RCC_D1CCIPR_FMCSEL_Pos, LL_RCC_FMC_CLKSOURCE_PLL2R ), RCC_CLK_MUX_FMC_HCLK ),
#elif defined(RCC_CDCCIPR_FMCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FMC_PLL2R             , RCC_BLOCK_FMC           , LL_CLKSOURCE( CDCCIP, RCC_CDCCIPR_FMCSEL, RCC_CDCCIPR_FMCSEL_Pos, LL_RCC_FMC_CLKSOURCE_PLL2R ), RCC_CLK_MUX_FMC_HCLK ),
#elif defined(RCC_CCIPR1_FMCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FMC_PLL2R             , RCC_BLOCK_FMC           , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_FMCSEL, RCC_CCIPR1_FMCSEL_Pos, LL_RCC_FMC_CLKSOURCE_PLL2R ), RCC_CLK_MUX_FMC_HCLK ),
#endif
#if defined(LL_RCC_FMC_CLKSOURCE_CLKP)
#if defined(RCC_D1CCIPR_FMCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FMC_LPCLK             , RCC_BLOCK_FMC           , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_FMCSEL, RCC_D1CCIPR_FMCSEL_Pos, LL_RCC_FMC_CLKSOURCE_CLKP ), RCC_CLK_MUX_FMC_HCLK ),
#elif defined(RCC_CDCCIPR_FMCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FMC_LPCLK             , RCC_BLOCK_FMC           , LL_CLKSOURCE( CDCCIP, RCC_CDCCIPR_FMCSEL, RCC_CDCCIPR_FMCSEL_Pos, LL_RCC_FMC_CLKSOURCE_CLKP ), RCC_CLK_MUX_FMC_HCLK ),
#endif
#endif
#if defined(LL_RCC_FMC_CLKSOURCE_HSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_FMC_HSI               , RCC_BLOCK_FMC           , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_FMCSEL, RCC_CCIPR1_FMCSEL_Pos, LL_RCC_FMC_CLKSOURCE_HSI ), RCC_CLK_MUX_FMC_HCLK ),
#endif
#if defined(LL_RCC_QSPI_CLKSOURCE_HCLK)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_QSPI_HCLK             , RCC_BLOCK_QSPI          , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_QSPISEL, RCC_D1CCIPR_QSPISEL_Pos, LL_RCC_QSPI_CLKSOURCE_HCLK ), RCC_CLK_MUX_QSPI_HCLK ),
#endif
#if defined(LL_RCC_QSPI_CLKSOURCE_PLL1Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_QSPI_PLL1Q            , RCC_BLOCK_QSPI          , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_QSPISEL, RCC_D1CCIPR_QSPISEL_Pos, LL_RCC_QSPI_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_QSPI_HCLK ),
#endif
#if defined(LL_RCC_QSPI_CLKSOURCE_PLL2R)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_QSPI_PLL2R            , RCC_BLOCK_QSPI          , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_QSPISEL, RCC_D1CCIPR_QSPISEL_Pos, LL_RCC_QSPI_CLKSOURCE_PLL2R ), RCC_CLK_MUX_QSPI_HCLK ),
#endif
#if defined(LL_RCC_QSPI_CLKSOURCE_CLKP)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_QSPI_LPCLK            , RCC_BLOCK_QSPI          , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_QSPISEL, RCC_D1CCIPR_QSPISEL_Pos, LL_RCC_QSPI_CLKSOURCE_CLKP ), RCC_CLK_MUX_QSPI_HCLK ),
#endif
#if defined(LL_RCC_OSPI_CLKSOURCE_HCLK)
#if defined(RCC_D1CCIPR_OCTOSPISEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_OSPI_HCLK             , RCC_BLOCK_OSPI1         , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_OCTOSPISEL, RCC_D1CCIPR_OCTOSPISEL_Pos, LL_RCC_OSPI_CLKSOURCE_HCLK ), RCC_CLK_MUX_OSPI_HCLK ),
#elif defined(RCC_CDCCIPR_OCTOSPISEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_OSPI_HCLK             , RCC_BLOCK_OSPI1         , LL_CLKSOURCE( CDCCIP, RCC_CDCCIPR_OCTOSPISEL, RCC_CDCCIPR_OCTOSPISEL_Pos, LL_RCC_OSPI_CLKSOURCE_HCLK ), RCC_CLK_MUX_OSPI_HCLK ),
#endif
#endif
#if defined(LL_RCC_OSPI_CLKSOURCE_PLL1Q)
#if defined(RCC_D1CCIPR_OCTOSPISEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_OSPI_PLL1Q            , RCC_BLOCK_OSPI1         , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_OCTOSPISEL, RCC_D1CCIPR_OCTOSPISEL_Pos, LL_RCC_OSPI_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_OSPI_HCLK ),
#elif defined(RCC_CDCCIPR_OCTOSPISEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_OSPI_PLL1Q            , RCC_BLOCK_OSPI1         , LL_CLKSOURCE( CDCCIP, RCC_CDCCIPR_OCTOSPISEL, RCC_CDCCIPR_OCTOSPISEL_Pos, LL_RCC_OSPI_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_OSPI_HCLK ),
#endif
#endif
#if defined(LL_RCC_OSPI_CLKSOURCE_PLL2R)
#if defined(RCC_D1CCIPR_OCTOSPISEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_OSPI_PLL2R            , RCC_BLOCK_OSPI1         , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_OCTOSPISEL, RCC_D1CCIPR_OCTOSPISEL_Pos, LL_RCC_OSPI_CLKSOURCE_PLL2R ), RCC_CLK_MUX_OSPI_HCLK ),
#elif defined(RCC_CDCCIPR_OCTOSPISEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_OSPI_PLL2R            , RCC_BLOCK_OSPI1         , LL_CLKSOURCE( CDCCIP, RCC_CDCCIPR_OCTOSPISEL, RCC_CDCCIPR_OCTOSPISEL_Pos, LL_RCC_OSPI_CLKSOURCE_PLL2R ), RCC_CLK_MUX_OSPI_HCLK ),
#endif
#endif
#if defined(LL_RCC_OSPI_CLKSOURCE_CLKP)
#if defined(RCC_D1CCIPR_OCTOSPISEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_OSPI_LPCLK            , RCC_BLOCK_OSPI1         , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_OCTOSPISEL, RCC_D1CCIPR_OCTOSPISEL_Pos, LL_RCC_OSPI_CLKSOURCE_CLKP ), RCC_CLK_MUX_OSPI_HCLK ),
#elif defined(RCC_CDCCIPR_OCTOSPISEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_OSPI_LPCLK            , RCC_BLOCK_OSPI1         , LL_CLKSOURCE( CDCCIP, RCC_CDCCIPR_OCTOSPISEL, RCC_CDCCIPR_OCTOSPISEL_Pos, LL_RCC_OSPI_CLKSOURCE_CLKP ), RCC_CLK_MUX_OSPI_HCLK ),
#endif
#endif
#if defined(RCC_D3CCIPR_ADCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_ADC_PLL2P             , RCC_BLOCK_ADC12         , LL_CLKSOURCE( D3CCIP, RCC_D3CCIPR_ADCSEL, RCC_D3CCIPR_ADCSEL_Pos, LL_RCC_ADC_CLKSOURCE_PLL2P ), RCC_CLK_MUX_ADC_PLL2P ),
#elif defined(RCC_SRDCCIPR_ADCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_ADC_PLL2P             , RCC_BLOCK_ADC12         , LL_CLKSOURCE( SRDCCIP, RCC_SRDCCIPR_ADCSEL, RCC_SRDCCIPR_ADCSEL_Pos, LL_RCC_ADC_CLKSOURCE_PLL2P ), RCC_CLK_MUX_ADC_PLL2P ),
#elif defined(RCC_CCIPR1_ADCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_ADC_PLL2P             , RCC_BLOCK_ADC12         , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_ADCSEL, RCC_CCIPR1_ADCSEL_Pos, LL_RCC_ADC_CLKSOURCE_PLL2P ), RCC_CLK_MUX_ADC_PLL2P ),
#endif
#if defined(RCC_D3CCIPR_ADCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_ADC_PLL3R             , RCC_BLOCK_ADC12         , LL_CLKSOURCE( D3CCIP, RCC_D3CCIPR_ADCSEL, RCC_D3CCIPR_ADCSEL_Pos, LL_RCC_ADC_CLKSOURCE_PLL3R ), RCC_CLK_MUX_ADC_PLL2P ),
#elif defined(RCC_SRDCCIPR_ADCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_ADC_PLL3R             , RCC_BLOCK_ADC12         , LL_CLKSOURCE( SRDCCIP, RCC_SRDCCIPR_ADCSEL, RCC_SRDCCIPR_ADCSEL_Pos, LL_RCC_ADC_CLKSOURCE_PLL3R ), RCC_CLK_MUX_ADC_PLL2P ),
#elif defined(RCC_CCIPR1_ADCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_ADC_PLL3R             , RCC_BLOCK_ADC12         , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_ADCSEL, RCC_CCIPR1_ADCSEL_Pos, LL_RCC_ADC_CLKSOURCE_PLL3R ), RCC_CLK_MUX_ADC_PLL2P ),
#endif
#if defined(RCC_D3CCIPR_ADCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_ADC_LPCLK             , RCC_BLOCK_ADC12         , LL_CLKSOURCE( D3CCIP, RCC_D3CCIPR_ADCSEL, RCC_D3CCIPR_ADCSEL_Pos, LL_RCC_ADC_CLKSOURCE_CLKP ), RCC_CLK_MUX_ADC_PLL2P ),
#elif defined(RCC_SRDCCIPR_ADCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_ADC_LPCLK             , RCC_BLOCK_ADC12         , LL_CLKSOURCE( SRDCCIP, RCC_SRDCCIPR_ADCSEL, RCC_SRDCCIPR_ADCSEL_Pos, LL_RCC_ADC_CLKSOURCE_CLKP ), RCC_CLK_MUX_ADC_PLL2P ),
#elif defined(RCC_CCIPR1_ADCSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_ADC_LPCLK             , RCC_BLOCK_ADC12         , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_ADCSEL, RCC_CCIPR1_ADCSEL_Pos, LL_RCC_ADC_CLKSOURCE_CLKP ), RCC_CLK_MUX_ADC_PLL2P ),
#endif
#if defined(RCC_D2CCIP2R_CECSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CEC_LSE               , RCC_BLOCK_CEC           , LL_CLKSOURCE( D2CCIP2, RCC_D2CCIP2R_CECSEL, RCC_D2CCIP2R_CECSEL_Pos, LL_RCC_CEC_CLKSOURCE_LSE ), RCC_CLK_MUX_CEC_LSE ),
#elif defined(RCC_CDCCIP2R_CECSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CEC_LSE               , RCC_BLOCK_CEC           , LL_CLKSOURCE( CDCCIP2, RCC_CDCCIP2R_CECSEL, RCC_CDCCIP2R_CECSEL_Pos, LL_RCC_CEC_CLKSOURCE_LSE ), RCC_CLK_MUX_CEC_LSE ),
#elif defined(RCC_CCIPR2_CECSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CEC_LSE               , RCC_BLOCK_CEC           , LL_CLKSOURCE( CCIPR2_OFFSET, RCC_CCIPR2_CECSEL, RCC_CCIPR2_CECSEL_Pos, LL_RCC_CEC_CLKSOURCE_LSE ), RCC_CLK_MUX_CEC_LSE ),
#endif
#if defined(RCC_D2CCIP2R_CECSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CEC_LSI               , RCC_BLOCK_CEC           , LL_CLKSOURCE( D2CCIP2, RCC_D2CCIP2R_CECSEL, RCC_D2CCIP2R_CECSEL_Pos, LL_RCC_CEC_CLKSOURCE_LSI ), RCC_CLK_MUX_CEC_LSE ),
#elif defined(RCC_CDCCIP2R_CECSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CEC_LSI               , RCC_BLOCK_CEC           , LL_CLKSOURCE( CDCCIP2, RCC_CDCCIP2R_CECSEL, RCC_CDCCIP2R_CECSEL_Pos, LL_RCC_CEC_CLKSOURCE_LSI ), RCC_CLK_MUX_CEC_LSE ),
#elif defined(RCC_CCIPR2_CECSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CEC_LSI               , RCC_BLOCK_CEC           , LL_CLKSOURCE( CCIPR2_OFFSET, RCC_CCIPR2_CECSEL, RCC_CCIPR2_CECSEL_Pos, LL_RCC_CEC_CLKSOURCE_LSI ), RCC_CLK_MUX_CEC_LSE ),
#endif
#if defined(LL_RCC_CEC_CLKSOURCE_CSI_DIV122)
#if defined(RCC_D2CCIP2R_CECSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CEC_CSI_DIV122        , RCC_BLOCK_CEC           , LL_CLKSOURCE( D2CCIP2, RCC_D2CCIP2R_CECSEL, RCC_D2CCIP2R_CECSEL_Pos, LL_RCC_CEC_CLKSOURCE_CSI_DIV122 ), RCC_CLK_MUX_CEC_LSE ),
#elif defined(RCC_CDCCIP2R_CECSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CEC_CSI_DIV122        , RCC_BLOCK_CEC           , LL_CLKSOURCE( CDCCIP2, RCC_CDCCIP2R_CECSEL, RCC_CDCCIP2R_CECSEL_Pos, LL_RCC_CEC_CLKSOURCE_CSI_DIV122 ), RCC_CLK_MUX_CEC_LSE ),
#endif
#elif defined(LL_RCC_CEC_CLKSOURCE_CSI_DIV_122)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CEC_CSI_DIV122        , RCC_BLOCK_CEC           , LL_CLKSOURCE( CCIPR2_OFFSET, RCC_CCIPR2_CECSEL, RCC_CCIPR2_CECSEL_Pos, LL_RCC_CEC_CLKSOURCE_CSI_DIV_122 ), RCC_CLK_MUX_CEC_LSE ),
#endif
#if defined(LL_RCC_DFSDM1_CLKSOURCE_PCLK2)
#if defined(RCC_D2CCIP1R_DFSDM1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_DFSDM1_PCLK2          , RCC_BLOCK_DFSDM1        , LL_CLKSOURCE( D2CCIP1, RCC_D2CCIP1R_DFSDM1SEL, RCC_D2CCIP1R_DFSDM1SEL_Pos, LL_RCC_DFSDM1_CLKSOURCE_PCLK2 ), RCC_CLK_MUX_DFSDM1_PCLK2 ),
#elif defined(RCC_CDCCIP1R_DFSDM1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_DFSDM1_PCLK2          , RCC_BLOCK_DFSDM1        , LL_CLKSOURCE( CDCCIP1, RCC_CDCCIP1R_DFSDM1SEL, RCC_CDCCIP1R_DFSDM1SEL_Pos, LL_RCC_DFSDM1_CLKSOURCE_PCLK2 ), RCC_CLK_MUX_DFSDM1_PCLK2 ),
#endif
#endif
#if defined(LL_RCC_DFSDM1_CLKSOURCE_SYSCLK)
#if defined(RCC_D2CCIP1R_DFSDM1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_DFSDM1_SYSCLK         , RCC_BLOCK_DFSDM1        , LL_CLKSOURCE( D2CCIP1, RCC_D2CCIP1R_DFSDM1SEL, RCC_D2CCIP1R_DFSDM1SEL_Pos, LL_RCC_DFSDM1_CLKSOURCE_SYSCLK ), RCC_CLK_MUX_DFSDM1_PCLK2 ),
#elif defined(RCC_CDCCIP1R_DFSDM1SEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_DFSDM1_SYSCLK         , RCC_BLOCK_DFSDM1        , LL_CLKSOURCE( CDCCIP1, RCC_CDCCIP1R_DFSDM1SEL, RCC_CDCCIP1R_DFSDM1SEL_Pos, LL_RCC_DFSDM1_CLKSOURCE_SYSCLK ), RCC_CLK_MUX_DFSDM1_PCLK2 ),
#endif
#endif
#if defined(LL_RCC_DFSDM2_CLKSOURCE_PCLK4)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_DFSDM2_PCLK4          , RCC_BLOCK_DFSDM2        , LL_CLKSOURCE( SRDCCIP, RCC_SRDCCIPR_DFSDM2SEL, RCC_SRDCCIPR_DFSDM2SEL_Pos, LL_RCC_DFSDM2_CLKSOURCE_PCLK4 ), RCC_CLK_MUX_DFSDM2_PCLK4 ),
#endif
#if defined(LL_RCC_DFSDM2_CLKSOURCE_SYSCLK)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_DFSDM2_SYSCLK         , RCC_BLOCK_DFSDM2        , LL_CLKSOURCE( SRDCCIP, RCC_SRDCCIPR_DFSDM2SEL, RCC_SRDCCIPR_DFSDM2SEL_Pos, LL_RCC_DFSDM2_CLKSOURCE_SYSCLK ), RCC_CLK_MUX_DFSDM2_PCLK4 ),
#endif
#if defined(LL_RCC_SWP_CLKSOURCE_PCLK1)
#if defined(RCC_D2CCIP1R_SWPSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SWP_PCLK1             , RCC_BLOCK_SWPMI         , LL_CLKSOURCE( D2CCIP1, RCC_D2CCIP1R_SWPSEL, RCC_D2CCIP1R_SWPSEL_Pos, LL_RCC_SWP_CLKSOURCE_PCLK1 ), RCC_CLK_MUX_SWP_PCLK1 ),
#elif defined(RCC_CDCCIP1R_SWPSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SWP_PCLK1             , RCC_BLOCK_SWPMI         , LL_CLKSOURCE( CDCCIP1, RCC_CDCCIP1R_SWPSEL, RCC_CDCCIP1R_SWPSEL_Pos, LL_RCC_SWP_CLKSOURCE_PCLK1 ), RCC_CLK_MUX_SWP_PCLK1 ),
#endif
#endif
#if defined(LL_RCC_SWP_CLKSOURCE_HSI)
#if defined(RCC_D2CCIP1R_SWPSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SWP_HSI               , RCC_BLOCK_SWPMI         , LL_CLKSOURCE( D2CCIP1, RCC_D2CCIP1R_SWPSEL, RCC_D2CCIP1R_SWPSEL_Pos, LL_RCC_SWP_CLKSOURCE_HSI ), RCC_CLK_MUX_SWP_PCLK1 ),
#elif defined(RCC_CDCCIP1R_SWPSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SWP_HSI               , RCC_BLOCK_SWPMI         , LL_CLKSOURCE( CDCCIP1, RCC_CDCCIP1R_SWPSEL, RCC_CDCCIP1R_SWPSEL_Pos, LL_RCC_SWP_CLKSOURCE_HSI ), RCC_CLK_MUX_SWP_PCLK1 ),
#endif
#endif
#if defined(LL_RCC_DSI_CLKSOURCE_PHY)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_DSI_PHY               , RCC_BLOCK_DSI           , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_DSISEL, RCC_D1CCIPR_DSISEL_Pos, LL_RCC_DSI_CLKSOURCE_PHY ), RCC_CLK_MUX_DSI_PHY ),
#endif
#if defined(LL_RCC_DSI_CLKSOURCE_PLL2Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_DSI_PLL2Q             , RCC_BLOCK_DSI           , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_DSISEL, RCC_D1CCIPR_DSISEL_Pos, LL_RCC_DSI_CLKSOURCE_PLL2Q ), RCC_CLK_MUX_DSI_PHY ),
#endif
#if defined(LL_RCC_USART1_CLKSOURCE_PCLK2)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART1_PCLK2          , RCC_BLOCK_USART1        , LL_RCC_USART1_CLKSOURCE_PCLK2, RCC_CLK_MUX_USART1_PCLK2 ),
#endif
#if defined(LL_RCC_USART1_CLKSOURCE_PLL2Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART1_PLL2Q          , RCC_BLOCK_USART1        , LL_RCC_USART1_CLKSOURCE_PLL2Q, RCC_CLK_MUX_USART1_PCLK2 ),
#endif
#if defined(LL_RCC_USART1_CLKSOURCE_PLL3Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART1_PLL3Q          , RCC_BLOCK_USART1        , LL_RCC_USART1_CLKSOURCE_PLL3Q, RCC_CLK_MUX_USART1_PCLK2 ),
#endif
#if defined(LL_RCC_USART1_CLKSOURCE_HSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART1_HSI            , RCC_BLOCK_USART1        , LL_RCC_USART1_CLKSOURCE_HSI, RCC_CLK_MUX_USART1_PCLK2 ),
#endif
#if defined(LL_RCC_USART1_CLKSOURCE_CSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART1_CSI            , RCC_BLOCK_USART1        , LL_RCC_USART1_CLKSOURCE_CSI, RCC_CLK_MUX_USART1_PCLK2 ),
#endif
#if defined(LL_RCC_USART1_CLKSOURCE_LSE)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USART1_LSE            , RCC_BLOCK_USART1        , LL_RCC_USART1_CLKSOURCE_LSE, RCC_CLK_MUX_USART1_PCLK2 ),
#endif
#if defined(LL_RCC_SPI1_CLKSOURCE_PLL1Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI1_PLL1Q            , RCC_BLOCK_SPI1          , LL_RCC_SPI1_CLKSOURCE_PLL1Q, RCC_CLK_MUX_SPI1_PLL1Q ),
#endif
#if defined(LL_RCC_SPI1_CLKSOURCE_PLL2P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI1_PLL2P            , RCC_BLOCK_SPI1          , LL_RCC_SPI1_CLKSOURCE_PLL2P, RCC_CLK_MUX_SPI1_PLL1Q ),
#endif
#if defined(LL_RCC_SPI1_CLKSOURCE_PLL3P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI1_PLL3P            , RCC_BLOCK_SPI1          , LL_RCC_SPI1_CLKSOURCE_PLL3P, RCC_CLK_MUX_SPI1_PLL1Q ),
#endif
#if defined(LL_RCC_SPI1_CLKSOURCE_I2S_CKIN)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI1_PIN              , RCC_BLOCK_SPI1          , LL_RCC_SPI1_CLKSOURCE_I2S_CKIN, RCC_CLK_MUX_SPI1_PLL1Q ),
#endif
#if defined(LL_RCC_SPI1_CLKSOURCE_CLKP)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI1_LPCLK            , RCC_BLOCK_SPI1          , LL_RCC_SPI1_CLKSOURCE_CLKP, RCC_CLK_MUX_SPI1_PLL1Q ),
#endif
#if defined(LL_RCC_SPI23_CLKSOURCE_PLL1Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI23_PLL1Q           , RCC_BLOCK_SPI2          , LL_RCC_SPI23_CLKSOURCE_PLL1Q, RCC_CLK_MUX_SPI23_PLL1Q ),
#endif
#if defined(LL_RCC_SPI23_CLKSOURCE_PLL2P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI23_PLL2P           , RCC_BLOCK_SPI2          , LL_RCC_SPI23_CLKSOURCE_PLL2P, RCC_CLK_MUX_SPI23_PLL1Q ),
#endif
#if defined(LL_RCC_SPI23_CLKSOURCE_PLL3P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI23_PLL3P           , RCC_BLOCK_SPI2          , LL_RCC_SPI23_CLKSOURCE_PLL3P, RCC_CLK_MUX_SPI23_PLL1Q ),
#endif
#if defined(LL_RCC_SPI23_CLKSOURCE_I2S_CKIN)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI23_PIN             , RCC_BLOCK_SPI2          , LL_RCC_SPI23_CLKSOURCE_I2S_CKIN, RCC_CLK_MUX_SPI23_PLL1Q ),
#endif
#if defined(LL_RCC_SPI23_CLKSOURCE_CLKP)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPI23_LPCLK           , RCC_BLOCK_SPI2          , LL_RCC_SPI23_CLKSOURCE_CLKP, RCC_CLK_MUX_SPI23_PLL1Q ),
#endif
#if defined(LL_RCC_I2C1_CLKSOURCE_PCLK1)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C1_PCLK1            , RCC_BLOCK_I2C1          , LL_RCC_I2C1_CLKSOURCE_PCLK1, RCC_CLK_MUX_I2C1_PCLK1 ),
#endif
#if defined(LL_RCC_I2C1_CLKSOURCE_PLL3R)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C1_PLL3R            , RCC_BLOCK_I2C1          , LL_RCC_I2C1_CLKSOURCE_PLL3R, RCC_CLK_MUX_I2C1_PCLK1 ),
#endif
#if defined(LL_RCC_I2C1_CLKSOURCE_HSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C1_HSI              , RCC_BLOCK_I2C1          , LL_RCC_I2C1_CLKSOURCE_HSI, RCC_CLK_MUX_I2C1_PCLK1 ),
#endif
#if defined(LL_RCC_I2C1_CLKSOURCE_CSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C1_CSI              , RCC_BLOCK_I2C1          , LL_RCC_I2C1_CLKSOURCE_CSI, RCC_CLK_MUX_I2C1_PCLK1 ),
#endif
#if defined(LL_RCC_I2C23_CLKSOURCE_PCLK1)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C23_PCLK1           , RCC_BLOCK_I2C2          , LL_RCC_I2C23_CLKSOURCE_PCLK1, RCC_CLK_MUX_I2C23_PCLK1 ),
#endif
#if defined(LL_RCC_I2C23_CLKSOURCE_PLL3R)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C23_PLL3R           , RCC_BLOCK_I2C2          , LL_RCC_I2C23_CLKSOURCE_PLL3R, RCC_CLK_MUX_I2C23_PCLK1 ),
#endif
#if defined(LL_RCC_I2C23_CLKSOURCE_HSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C23_HSI             , RCC_BLOCK_I2C2          , LL_RCC_I2C23_CLKSOURCE_HSI, RCC_CLK_MUX_I2C23_PCLK1 ),
#endif
#if defined(LL_RCC_I2C23_CLKSOURCE_CSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_I2C23_CSI             , RCC_BLOCK_I2C2          , LL_RCC_I2C23_CLKSOURCE_CSI, RCC_CLK_MUX_I2C23_PCLK1 ),
#endif
#if defined(LL_RCC_LPTIM23_CLKSOURCE_PCLK4)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM23_PCLK4         , RCC_BLOCK_LPTIM2        , LL_RCC_LPTIM23_CLKSOURCE_PCLK4, RCC_CLK_MUX_LPTIM23_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM23_CLKSOURCE_PLL2P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM23_PLL2P         , RCC_BLOCK_LPTIM2        , LL_RCC_LPTIM23_CLKSOURCE_PLL2P, RCC_CLK_MUX_LPTIM23_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM23_CLKSOURCE_PLL3R)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM23_PLL3R         , RCC_BLOCK_LPTIM2        , LL_RCC_LPTIM23_CLKSOURCE_PLL3R, RCC_CLK_MUX_LPTIM23_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM23_CLKSOURCE_LSE)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM23_LSE           , RCC_BLOCK_LPTIM2        , LL_RCC_LPTIM23_CLKSOURCE_LSE, RCC_CLK_MUX_LPTIM23_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM23_CLKSOURCE_LSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM23_LSI           , RCC_BLOCK_LPTIM2        , LL_RCC_LPTIM23_CLKSOURCE_LSI, RCC_CLK_MUX_LPTIM23_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM23_CLKSOURCE_CLKP)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM23_LPCLK         , RCC_BLOCK_LPTIM2        , LL_RCC_LPTIM23_CLKSOURCE_CLKP, RCC_CLK_MUX_LPTIM23_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM45_CLKSOURCE_PCLK4)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM45_PCLK4         , RCC_BLOCK_LPTIM4        , LL_RCC_LPTIM45_CLKSOURCE_PCLK4, RCC_CLK_MUX_LPTIM45_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM45_CLKSOURCE_PLL2P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM45_PLL2P         , RCC_BLOCK_LPTIM4        , LL_RCC_LPTIM45_CLKSOURCE_PLL2P, RCC_CLK_MUX_LPTIM45_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM45_CLKSOURCE_PLL3R)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM45_PLL3R         , RCC_BLOCK_LPTIM4        , LL_RCC_LPTIM45_CLKSOURCE_PLL3R, RCC_CLK_MUX_LPTIM45_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM45_CLKSOURCE_LSE)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM45_LSE           , RCC_BLOCK_LPTIM4        , LL_RCC_LPTIM45_CLKSOURCE_LSE, RCC_CLK_MUX_LPTIM45_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM45_CLKSOURCE_LSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM45_LSI           , RCC_BLOCK_LPTIM4        , LL_RCC_LPTIM45_CLKSOURCE_LSI, RCC_CLK_MUX_LPTIM45_PCLK4 ),
#endif
#if defined(LL_RCC_LPTIM45_CLKSOURCE_CLKP)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_LPTIM45_LPCLK         , RCC_BLOCK_LPTIM4        , LL_RCC_LPTIM45_CLKSOURCE_CLKP, RCC_CLK_MUX_LPTIM45_PCLK4 ),
#endif
#if defined(LL_RCC_SAI2_CLKSOURCE_PLL1Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2_PLL1Q            , RCC_BLOCK_SAI2          , LL_RCC_SAI2_CLKSOURCE_PLL1Q, RCC_CLK_MUX_SAI2_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2_CLKSOURCE_PLL2P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2_PLL2P            , RCC_BLOCK_SAI2          , LL_RCC_SAI2_CLKSOURCE_PLL2P, RCC_CLK_MUX_SAI2_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2_CLKSOURCE_PLL3P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2_PLL3P            , RCC_BLOCK_SAI2          , LL_RCC_SAI2_CLKSOURCE_PLL3P, RCC_CLK_MUX_SAI2_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2_CLKSOURCE_I2S_CKIN)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2_PIN              , RCC_BLOCK_SAI2          , LL_RCC_SAI2_CLKSOURCE_I2S_CKIN, RCC_CLK_MUX_SAI2_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2_CLKSOURCE_CLKP)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2_LPCLK            , RCC_BLOCK_SAI2          , LL_RCC_SAI2_CLKSOURCE_CLKP, RCC_CLK_MUX_SAI2_PLL1Q ),
#endif
#if defined(LL_RCC_SAI2_CLKSOURCE_SPDIFRX)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SAI2_SPDIF            , RCC_BLOCK_SAI2          , LL_RCC_SAI2_CLKSOURCE_SPDIFRX, RCC_CLK_MUX_SAI2_PLL1Q ),
#endif
#if defined(LL_RCC_SPDIFRX_CLKSOURCE_PLL1Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPDIFRX_PLL1Q         , RCC_BLOCK_SPDIFRX       , LL_CLKSOURCE( CCIPR2_OFFSET, RCC_CCIPR2_SPDIFRXSEL, RCC_CCIPR2_SPDIFRXSEL_Pos, LL_RCC_SPDIFRX_CLKSOURCE_PLL1Q ), RCC_CLK_MUX_SPDIFRX_PLL1Q ),
#endif
#if defined(LL_RCC_SPDIFRX_CLKSOURCE_PLL2R)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPDIFRX_PLL2R         , RCC_BLOCK_SPDIFRX       , LL_CLKSOURCE( CCIPR2_OFFSET, RCC_CCIPR2_SPDIFRXSEL, RCC_CCIPR2_SPDIFRXSEL_Pos, LL_RCC_SPDIFRX_CLKSOURCE_PLL2R ), RCC_CLK_MUX_SPDIFRX_PLL1Q ),
#endif
#if defined(LL_RCC_SPDIFRX_CLKSOURCE_PLL3R)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPDIFRX_PLL3R         , RCC_BLOCK_SPDIFRX       , LL_CLKSOURCE( CCIPR2_OFFSET, RCC_CCIPR2_SPDIFRXSEL, RCC_CCIPR2_SPDIFRXSEL_Pos, LL_RCC_SPDIFRX_CLKSOURCE_PLL3R ), RCC_CLK_MUX_SPDIFRX_PLL1Q ),
#endif
#if defined(LL_RCC_SPDIFRX_CLKSOURCE_HSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_SPDIFRX_HSI           , RCC_BLOCK_SPDIFRX       , LL_CLKSOURCE( CCIPR2_OFFSET, RCC_CCIPR2_SPDIFRXSEL, RCC_CCIPR2_SPDIFRXSEL_Pos, LL_RCC_SPDIFRX_CLKSOURCE_HSI ), RCC_CLK_MUX_SPDIFRX_PLL1Q ),
#endif
#if defined(LL_RCC_XSPI1_CLKSOURCE_HCLK)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_XSPI1_HCLK            , RCC_BLOCK_XSPI1         , LL_RCC_XSPI1_CLKSOURCE_HCLK, RCC_CLK_MUX_XSPI1_HCLK ),
#endif
#if defined(LL_RCC_XSPI1_CLKSOURCE_PLL2S)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_XSPI1_PLL2S           , RCC_BLOCK_XSPI1         , LL_RCC_XSPI1_CLKSOURCE_PLL2S, RCC_CLK_MUX_XSPI1_HCLK ),
#endif
#if defined(LL_RCC_XSPI1_CLKSOURCE_PLL2T)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_XSPI1_PLL2T           , RCC_BLOCK_XSPI1         , LL_RCC_XSPI1_CLKSOURCE_PLL2T, RCC_CLK_MUX_XSPI1_HCLK ),
#endif
#if defined(LL_RCC_XSPI2_CLKSOURCE_HCLK)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_XSPI2_HCLK            , RCC_BLOCK_XSPI2         , LL_RCC_XSPI2_CLKSOURCE_HCLK, RCC_CLK_MUX_XSPI2_HCLK ),
#endif
#if defined(LL_RCC_XSPI2_CLKSOURCE_PLL2S)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_XSPI2_PLL2S           , RCC_BLOCK_XSPI2         , LL_RCC_XSPI2_CLKSOURCE_PLL2S, RCC_CLK_MUX_XSPI2_HCLK ),
#endif
#if defined(LL_RCC_XSPI2_CLKSOURCE_PLL2T)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_XSPI2_PLL2T           , RCC_BLOCK_XSPI2         , LL_RCC_XSPI2_CLKSOURCE_PLL2T, RCC_CLK_MUX_XSPI2_HCLK ),
#endif
#if defined(LL_RCC_ADF1_CLKSOURCE_HCLK)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_ADF1_HCLK             , RCC_BLOCK_ADF1          , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_ADF1SEL, RCC_CCIPR1_ADF1SEL_Pos, LL_RCC_ADF1_CLKSOURCE_HCLK ), RCC_CLK_MUX_ADF1_HCLK ),
#endif
#if defined(LL_RCC_ADF1_CLKSOURCE_PLL2P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_ADF1_PLL2P            , RCC_BLOCK_ADF1          , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_ADF1SEL, RCC_CCIPR1_ADF1SEL_Pos, LL_RCC_ADF1_CLKSOURCE_PLL2P ), RCC_CLK_MUX_ADF1_HCLK ),
#endif
#if defined(LL_RCC_ADF1_CLKSOURCE_PLL3P)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_ADF1_PLL3P            , RCC_BLOCK_ADF1          , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_ADF1SEL, RCC_CCIPR1_ADF1SEL_Pos, LL_RCC_ADF1_CLKSOURCE_PLL3P ), RCC_CLK_MUX_ADF1_HCLK ),
#endif
#if defined(LL_RCC_ADF1_CLKSOURCE_I2S_CKIN)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_ADF1_PIN              , RCC_BLOCK_ADF1          , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_ADF1SEL, RCC_CCIPR1_ADF1SEL_Pos, LL_RCC_ADF1_CLKSOURCE_I2S_CKIN ), RCC_CLK_MUX_ADF1_HCLK ),
#endif
#if defined(LL_RCC_ADF1_CLKSOURCE_CSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_ADF1_CSI              , RCC_BLOCK_ADF1          , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_ADF1SEL, RCC_CCIPR1_ADF1SEL_Pos, LL_RCC_ADF1_CLKSOURCE_CSI ), RCC_CLK_MUX_ADF1_HCLK ),
#endif
#if defined(LL_RCC_ADF1_CLKSOURCE_HSI)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_ADF1_HSI              , RCC_BLOCK_ADF1          , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_ADF1SEL, RCC_CCIPR1_ADF1SEL_Pos, LL_RCC_ADF1_CLKSOURCE_HSI ), RCC_CLK_MUX_ADF1_HCLK ),
#endif
#if defined(LL_RCC_OTGFS_CLKSOURCE_HSI48)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_OTGFS_HSI48           , RCC_BLOCK_OTGFS         , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_OTGFSSEL, RCC_CCIPR1_OTGFSSEL_Pos, LL_RCC_OTGFS_CLKSOURCE_HSI48 ), RCC_CLK_MUX_OTGFS_HSI48 ),
#endif
#if defined(LL_RCC_OTGFS_CLKSOURCE_PLL3Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_OTGFS_PLL3Q           , RCC_BLOCK_OTGFS         , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_OTGFSSEL, RCC_CCIPR1_OTGFSSEL_Pos, LL_RCC_OTGFS_CLKSOURCE_PLL3Q ), RCC_CLK_MUX_OTGFS_HSI48 ),
#endif
#if defined(LL_RCC_OTGFS_CLKSOURCE_HSE)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_OTGFS_HSE             , RCC_BLOCK_OTGFS         , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_OTGFSSEL, RCC_CCIPR1_OTGFSSEL_Pos, LL_RCC_OTGFS_CLKSOURCE_HSE ), RCC_CLK_MUX_OTGFS_HSI48 ),
#endif
#if defined(LL_RCC_OTGFS_CLKSOURCE_CLK48)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_OTGFS_CLK48           , RCC_BLOCK_OTGFS         , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_OTGFSSEL, RCC_CCIPR1_OTGFSSEL_Pos, LL_RCC_OTGFS_CLKSOURCE_CLK48 ), RCC_CLK_MUX_OTGFS_HSI48 ),
#endif
#if defined(LL_RCC_USBPHYC_CLKSOURCE_HSE)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USBPHYC_HSE           , RCC_BLOCK_USBPHYC       , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_USBPHYCSEL, RCC_CCIPR1_USBPHYCSEL_Pos, LL_RCC_USBPHYC_CLKSOURCE_HSE ), RCC_CLK_MUX_USBPHYC_HSE ),
#endif
#if defined(LL_RCC_USBPHYC_CLKSOURCE_HSE_DIV_2)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USBPHYC_HSE_DIV2      , RCC_BLOCK_USBPHYC       , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_USBPHYCSEL, RCC_CCIPR1_USBPHYCSEL_Pos, LL_RCC_USBPHYC_CLKSOURCE_HSE_DIV_2 ), RCC_CLK_MUX_USBPHYC_HSE ),
#endif
#if defined(LL_RCC_USBPHYC_CLKSOURCE_PLL3Q)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USBPHYC_PLL3Q         , RCC_BLOCK_USBPHYC       , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_USBPHYCSEL, RCC_CCIPR1_USBPHYCSEL_Pos, LL_RCC_USBPHYC_CLKSOURCE_PLL3Q ), RCC_CLK_MUX_USBPHYC_HSE ),
#endif
#if defined(LL_RCC_USBPHYC_CLKSOURCE_DISABLE)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_USBPHYC_DISABLE       , RCC_BLOCK_USBPHYC       , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_USBPHYCSEL, RCC_CCIPR1_USBPHYCSEL_Pos, LL_RCC_USBPHYC_CLKSOURCE_DISABLE ), RCC_CLK_MUX_USBPHYC_HSE ),
#endif
#if defined(LL_RCC_PSSI_CLKSOURCE_PLL3R)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_PSSI_PLL3R            , RCC_BLOCK_PSSI          , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_PSSISEL, RCC_CCIPR1_PSSISEL_Pos, LL_RCC_PSSI_CLKSOURCE_PLL3R ), RCC_CLK_MUX_PSSI_PLL3R ),
#endif
#if defined(LL_RCC_PSSI_CLKSOURCE_CLKP)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_PSSI_LPCLK            , RCC_BLOCK_PSSI          , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_PSSISEL, RCC_CCIPR1_PSSISEL_Pos, LL_RCC_PSSI_CLKSOURCE_CLKP ), RCC_CLK_MUX_PSSI_PLL3R ),
#endif
#if defined(RCC_D1CCIPR_CKPERSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CLKP_HSI              , RCC_BLOCK_CKPER         , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_CKPERSEL, RCC_D1CCIPR_CKPERSEL_Pos, LL_RCC_CLKP_CLKSOURCE_HSI ), RCC_CLK_MUX_CLKP_HSI ),
#elif defined(RCC_CDCCIPR_CKPERSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CLKP_HSI              , RCC_BLOCK_CKPER         , LL_CLKSOURCE( CDCCIP, RCC_CDCCIPR_CKPERSEL, RCC_CDCCIPR_CKPERSEL_Pos, LL_RCC_CLKP_CLKSOURCE_HSI ), RCC_CLK_MUX_CLKP_HSI ),
#elif defined(RCC_CCIPR1_CKPERSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CLKP_HSI              , RCC_BLOCK_CKPER         , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_CKPERSEL, RCC_CCIPR1_CKPERSEL_Pos, LL_RCC_CLKP_CLKSOURCE_HSI ), RCC_CLK_MUX_CLKP_HSI ),
#endif
#if defined(RCC_D1CCIPR_CKPERSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CLKP_CSI              , RCC_BLOCK_CKPER         , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_CKPERSEL, RCC_D1CCIPR_CKPERSEL_Pos, LL_RCC_CLKP_CLKSOURCE_CSI ), RCC_CLK_MUX_CLKP_HSI ),
#elif defined(RCC_CDCCIPR_CKPERSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CLKP_CSI              , RCC_BLOCK_CKPER         , LL_CLKSOURCE( CDCCIP, RCC_CDCCIPR_CKPERSEL, RCC_CDCCIPR_CKPERSEL_Pos, LL_RCC_CLKP_CLKSOURCE_CSI ), RCC_CLK_MUX_CLKP_HSI ),
#elif defined(RCC_CCIPR1_CKPERSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CLKP_CSI              , RCC_BLOCK_CKPER         , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_CKPERSEL, RCC_CCIPR1_CKPERSEL_Pos, LL_RCC_CLKP_CLKSOURCE_CSI ), RCC_CLK_MUX_CLKP_HSI ),
#endif
#if defined(RCC_D1CCIPR_CKPERSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CLKP_HSE              , RCC_BLOCK_CKPER         , LL_CLKSOURCE( D1CCIP, RCC_D1CCIPR_CKPERSEL, RCC_D1CCIPR_CKPERSEL_Pos, LL_RCC_CLKP_CLKSOURCE_HSE ), RCC_CLK_MUX_CLKP_HSI ),
#elif defined(RCC_CDCCIPR_CKPERSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CLKP_HSE              , RCC_BLOCK_CKPER         , LL_CLKSOURCE( CDCCIP, RCC_CDCCIPR_CKPERSEL, RCC_CDCCIPR_CKPERSEL_Pos, LL_RCC_CLKP_CLKSOURCE_HSE ), RCC_CLK_MUX_CLKP_HSI ),
#elif defined(RCC_CCIPR1_CKPERSEL)
  RCC_CLK_MUX_RECORD( RCC_CLK_MUX_CLKP_HSE              , RCC_BLOCK_CKPER         , LL_CLKSOURCE( CCIPR1_OFFSET, RCC_CCIPR1_CKPERSEL, RCC_CCIPR1_CKPERSEL_Pos, LL_RCC_CLKP_CLKSOURCE_HSE ), RCC_CLK_MUX_CLKP_HSI ),
#endif
};

_Static_assert( (sizeof(rcc_ClkMuxConfig) / sizeof(rcc_ClkMuxConfigStruct_t)) == RCC_CLK_MUX_LIST_CNT, "Rcc_ClkMux: rcc_ClkMuxConfig has incorrect size." );

/* ========================= EXPORTED FUNCTIONS ============================= */

/**
 * \brief Initializes peripheral clock multiplexer module.
 *
 * \return State of request execution. Returns "OK" if request was success,
 *         otherwise return error.
 */
rcc_RequestState_t Rcc_ClkMux_Init( void )
{
    rcc_RequestState_t retState = RCC_REQUEST_OK;

    for( rcc_ClkMuxId_t clkMuxId = 0u; RCC_CLK_MUX_LIST_CNT > clkMuxId; clkMuxId++ )
    {
        const rcc_RequestState_t recordState = Rcc_ClkMux_Check_Record( clkMuxId );

        if( clkMuxId != rcc_ClkMuxConfig[ clkMuxId ].ClkMuxId )
        {
            /* Configuration error: Indexes do not match */
            retState = RCC_REQUEST_ERROR;
            break;
        }
        else if( RCC_REQUEST_OK != recordState )
        {
            /* Configuration error: Clock source value does not belong to the multiplexer field */
            retState = RCC_REQUEST_ERROR;
            break;
        }
        else
        {
            /* Record is valid, proceed to next entry */
        }
    }

    return ( retState );
}


/**
 * \brief De-initializes peripheral clock multiplexer module.
 */
void Rcc_ClkMux_Deinit( void )
{
    return;
}


/**
 * \brief Main task of peripheral clock multiplexer module.
 */
void Rcc_ClkMux_Task( void )
{
    return;
}


/**
 * \brief Sets the peripheral clock multiplexer to required clock source.
 *
 * \warning To change the clock source of a peripheral, first the peripheral
 * must be disabled by setting the clock multiplexer to its default value.
 * Selection of the already selected clock source is accepted.
 *
 * \param clkMuxId [in]: Peripheral clock source identifier
 *
 * \return State of request execution. Returns "OK" if request was success,
 *         otherwise return error.
 */
rcc_RequestState_t Rcc_ClkMux_Set_ClkActive( rcc_ClkMuxId_t clkMuxId  )
{
    rcc_RequestState_t retState = RCC_REQUEST_ERROR;
    uint32_t           regValue = 0u;

    if( RCC_CLK_MUX_LIST_CNT > clkMuxId )
    {
        uint32_t    ctrlRegVal  = Rcc_ClkMux_Get_FieldVal( clkMuxId );
        uint32_t    ctrlRegMask = rcc_ClkMuxConfig[ clkMuxId ].ClkSrcMask;
        rcc_RegId_t ctrlRegId   = rcc_ClkMuxConfig[ clkMuxId ].ClkMuxRegId;

        rcc_ClkMuxId_t defaultClkMuxId   = rcc_ClkMuxConfig[ clkMuxId ].DefaultClkMuxId;
        uint32_t       defaultCtrlRegVal = Rcc_ClkMux_Get_FieldVal( defaultClkMuxId );

        /* Check if the clock multiplexer is set to default value (or already to required value). */
        uint32_t actualRegVal = Rcc_Get_RegVal( ctrlRegId, ctrlRegMask );

        if( ( actualRegVal == defaultCtrlRegVal ) ||
            ( actualRegVal == ctrlRegVal        )    )
        {
            Rcc_Set_RegVal( ctrlRegId, ctrlRegMask, ctrlRegVal );

            for( uint32_t iterationCnt = 0u; RCC_CLKMUX_TIMEOUT_RAW > iterationCnt; iterationCnt ++ )
            {
                regValue = Rcc_Get_RegVal( ctrlRegId, ctrlRegMask);

                if( regValue == ctrlRegVal )
                {
                    retState = RCC_REQUEST_OK;
                    break;
                }
                else
                {
                    retState = RCC_REQUEST_ERROR;
                }
            }
        }
        else
        {
            /* To configure the clock multiplexer, first set it to default
             * value by disabling peripheral. */
            retState = RCC_REQUEST_ERROR;
        }
    }
    else
    {
        retState = RCC_REQUEST_ERROR;
    }

    return ( retState );
}


/**
 * \brief Sets the peripheral clock multiplexer to default clock source.
 *
 * \param clkMuxId [in]: Peripheral clock source identifier
 *
 * \return State of request execution. Returns "OK" if request was success,
 *         otherwise return error.
 */
rcc_RequestState_t Rcc_ClkMux_Set_ClkInactive( rcc_ClkMuxId_t clkMuxId  )
{
    rcc_RequestState_t retState = RCC_REQUEST_ERROR;
    uint32_t           regValue = 0u;

    if( RCC_CLK_MUX_LIST_CNT > clkMuxId )
    {
        uint32_t    ctrlRegMask = rcc_ClkMuxConfig[ clkMuxId ].ClkSrcMask;
        rcc_RegId_t ctrlRegId   = rcc_ClkMuxConfig[ clkMuxId ].ClkMuxRegId;

        rcc_ClkMuxId_t defaultClkMuxId   = rcc_ClkMuxConfig[ clkMuxId ].DefaultClkMuxId;
        uint32_t       defaultCtrlRegVal = Rcc_ClkMux_Get_FieldVal( defaultClkMuxId );

        Rcc_Set_RegVal( ctrlRegId, ctrlRegMask, defaultCtrlRegVal );

        for( uint32_t iterationCnt = 0u; RCC_CLKMUX_TIMEOUT_RAW > iterationCnt; iterationCnt ++ )
        {
            regValue = Rcc_Get_RegVal( ctrlRegId, ctrlRegMask);

            if( regValue == defaultCtrlRegVal )
            {
                retState = RCC_REQUEST_OK;
                break;
            }
            else
            {
                retState = RCC_REQUEST_ERROR;
            }
        }
    }
    else
    {
        retState = RCC_REQUEST_ERROR;
    }

    return ( retState );
}


/**
 * \brief Returns the peripheral clock multiplexer for required clock source.
 *
 * \param clkMuxIdIn [in]: Any clock multiplexer ID of the peripheral (identifies the multiplexer), value from \ref rcc_ClkMuxId_t.
 * \param clkMuxId  [out]: Peripheral clock source identifier
 *
 * \return State of request execution. Returns "OK" if request was success,
 *         otherwise return error.
 */
rcc_RequestState_t Rcc_ClkMux_Get_ClkSrc( rcc_ClkMuxId_t clkMuxIdIn, rcc_ClkMuxId_t * const clkMuxId )
{
    rcc_RequestState_t retState = RCC_REQUEST_ERROR;

    if( ( RCC_NULL_PTR        != clkMuxId   ) &&
        ( RCC_CLK_MUX_LIST_CNT > clkMuxIdIn )    )
    {
        const rcc_ClkMuxId_t  defaultClkMux = rcc_ClkMuxConfig[ clkMuxIdIn ].DefaultClkMuxId;
        const rcc_BlockList_t blockId       = rcc_ClkMuxConfig[ clkMuxIdIn ].BlockId;

        uint32_t    ctrlRegMask = rcc_ClkMuxConfig[ clkMuxIdIn ].ClkSrcMask;
        rcc_RegId_t ctrlRegId   = rcc_ClkMuxConfig[ clkMuxIdIn ].ClkMuxRegId;

        /* Actual multiplexer value is searched in consecutive entries of the same multiplexer */
        uint32_t actualRegVal = Rcc_Get_RegVal( ctrlRegId, ctrlRegMask );

        *clkMuxId = RCC_CLK_MUX_LIST_CNT;

        for( rcc_ClkMuxId_t muxId = defaultClkMux; ( RCC_CLK_MUX_LIST_CNT > muxId                               ) &&
                                                   ( blockId       == rcc_ClkMuxConfig[ muxId ].BlockId         ) &&
                                                   ( defaultClkMux == rcc_ClkMuxConfig[ muxId ].DefaultClkMuxId );    muxId ++ )
        {
            const uint32_t recordFieldVal = Rcc_ClkMux_Get_FieldVal( muxId );

            if( recordFieldVal == actualRegVal )
            {
                *clkMuxId = rcc_ClkMuxConfig[ muxId ].ClkMuxId;
                retState  = RCC_REQUEST_OK;
                break;
            }
            else
            {
                /* Continue with next entry of the block */
            }
        }
    }
    else
    {
        retState = RCC_REQUEST_ERROR;
    }

    return ( retState );
}

/* =========================== LOCAL FUNCTIONS ============================== */

/**
 * \brief Returns the multiplexer field value (masked, not shifted) selecting the clock source of the record.
 *
 * ClkSrcVal holds either the raw field value (always within ClkSrcMask) or the
 * LL_CLKSOURCE() encoded value (bits outside of ClkSrcMask - register offset,
 * position and mask), which is converted by LL_CLKSOURCE_CONFIG().
 *
 * \param clkMuxId [in]: Clock multiplexer record identifier (must be valid)
 *
 * \return Field value to be written to / compared with the masked register value.
 */
static uint32_t Rcc_ClkMux_Get_FieldVal( rcc_ClkMuxId_t clkMuxId )
{
    const uint32_t clkSrcVal  = rcc_ClkMuxConfig[ clkMuxId ].ClkSrcVal;
    const uint32_t clkSrcMask = rcc_ClkMuxConfig[ clkMuxId ].ClkSrcMask;
    uint32_t       fieldVal   = clkSrcVal;

    if( 0u != ( clkSrcVal & ~clkSrcMask ) )
    {
        /* LL_CLKSOURCE() encoded value */
        fieldVal = LL_CLKSOURCE_CONFIG( clkSrcVal );
    }
    else
    {
        /* Raw field value */
    }

    return ( fieldVal );
}


/**
 * \brief Checks that the clock source value of the record belongs to the multiplexer field of the record.
 *
 * \param clkMuxId [in]: Clock multiplexer record identifier (must be valid)
 *
 * \return Returns "OK" if the raw value lies within ClkSrcMask or the encoded value
 *         describes the same field (mask), otherwise returns error.
 */
static rcc_RequestState_t Rcc_ClkMux_Check_Record( rcc_ClkMuxId_t clkMuxId )
{
    rcc_RequestState_t retState   = RCC_REQUEST_ERROR;
    const uint32_t     clkSrcVal  = rcc_ClkMuxConfig[ clkMuxId ].ClkSrcVal;
    const uint32_t     clkSrcMask = rcc_ClkMuxConfig[ clkMuxId ].ClkSrcMask;

    if( 0u == ( clkSrcVal & ~clkSrcMask ) )
    {
        /* Raw field value */
        retState = RCC_REQUEST_OK;
    }
    else if( clkSrcMask == LL_CLKSOURCE_MASK( clkSrcVal ) )
    {
        /* LL_CLKSOURCE() encoded value of the same field */
        retState = RCC_REQUEST_OK;
    }
    else
    {
        retState = RCC_REQUEST_ERROR;
    }

    return ( retState );
}

/* =========================== INTERRUPT HANDLERS =========================== */

/* ================================ TASKS =================================== */
